### ISSUE TITLE
Fix sample data ogr.CreateGeometryFromWkt() error

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#100]
Examples:

* http://data.openaddresses.io/runs/1429251191.158/us-pa-beaver.txt
* http://data.openaddresses.io/runs/1429251191.158/us-ia-polk.txt
* http://data.openaddresses.io/runs/1429251191.158/us-la-lafayette.txt

**Comment by migurski** [comment]
All of these turn out to be cases of layers without features, and the error thrown is now a more informative `StopIteration`.

**Comment by iandees** [comment]
FWIW in the esri code I skip data with no geometry rather than raising
StopIteration.

**Comment by migurski** [comment]
Might explain some of the empty datasets that led to this issue.
