### ISSUE TITLE
Fix recognition of commas as decimal separators

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#102]
[Iceland](https://github.com/openaddresses/openaddresses/blob/master/sources/is.json) uses values like `64,1105792127745` to represent floating point degrees, which are interpreted as integers.

**Comment by NelsonMinar** [comment]
Fixed, verified Iceland processes. While looking into this I realized our whole system is locale-dependent. Python uses the system locale for the float() function, probably all sorts of other stuff. I've ignored locale with my fix. We should probably ensure our code sets the locale some day.

http://i.imgur.com/Ft4B4S4.jpg

**Comment by NelsonMinar** [comment]
![61421841](https://cloud.githubusercontent.com/assets/382136/7217801/b02faf4a-e5fa-11e4-936e-1ad690a8e3d8.jpg)
