### ISSUE TITLE
Fix incorrect file selection

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#104]
[Utah](https://github.com/openaddresses/openaddresses/blob/master/sources/us-ut.json) names a file that is present in the source zip, but [on a recent run it failed to extract](http://data.openaddresses.io/runs/1429510238.960/us-ut.txt). Why?

**Comment by kreed** [comment]
Seems to be a case mismatch. `elaborate_filenames` is converting filenames to lowercase but ZipDecompressTask is looking for the original case.

**Comment by migurski** [comment]
Waiting for tonight’s batch run to see if [the Utah issue](http://data.openaddresses.io/runs/1432534137.797/us-ut.txt) disappears.

**Comment by migurski** [comment]
[It’s back](http://data.openaddresses.io/runs/1432707295.484/us-ut.txt)!
