### ISSUE TITLE
Introduce ci.worker time limit

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#116]
I want to introduce a time limit to `openaddr.ci.worker` [near the subprocess call](https://github.com/openaddresses/machine/blob/1.9.2/openaddr/ci/worker.py#L41), to prevent runaway sources and possibly implement queue retries. It should match [`openaddr.ci.jobs.global_job_timeout` if possible](https://github.com/openaddresses/machine/blob/1.9.2/openaddr/jobs.py#L29). @NelsonMinar, you wrote a lot of the job control, how might that work?

**Comment by NelsonMinar** [comment]
I think the best solution is to add the `timeout` parameter to the subprocess call. That option was added in Python 3.3 and was backported to Py2: see [subprocess32](https://pypi.python.org/pypi/subprocess32/). This will make the parent process responsible for the timeout, which seems best.

Another way would be to add the [timeout decorator from the batch runner](https://github.com/openaddresses/machine/blob/master/openaddr/jobs.py#L50-L76) inside the `openaddr-process-one` program. But that doesn't feel quite right to me; it's relying on the child job to time itself out.

A third way would be to add more code to the parent launcher to implement a timeout there. I think that ends up being functionally equivalent to just using the new stuff in subprocess.

Much discussion in [this StackExchange thread](http://stackoverflow.com/questions/1191374/subprocess-with-timeout). Some of the top voted answers are wrong. I'm proposing [this answer](http://stackoverflow.com/a/12698328/144170).

**Comment by migurski** [comment]
I like that new stuff; subprocess32 sounds like a winner. We can get it into `openaddr.compat`. Thank you!

**Comment by migurski** [comment]
If we move away from the batch process, most of `openaddr.jobs` could disappear—is that right?

**Comment by NelsonMinar** [comment]
Yeah, I think so. Most of `openaddr.jobs` is the complex multiprocessing batch runner, trying to run all sources reliably with N processes at once. Now we have a new way to run sources. We still need to have a way to run more than one worker at once. I think that will Just Work if we spin up more than one worker process. We may find our job queue system is a scaling bottleneck, but I doubt it. We'd also need a way to create a batch of jobs to run, say, weekly to update stuff. And collect results to `data.openaddresses.io` and all that.
