### ISSUE TITLE
Tweak conform to allow ESRI FileGDB sources

### ISSUE THREAD

**Issue by iandees** [openaddresses/machine#150]
Indiana's [statewide address source](http://data.openaddresses.io/runs/1436163265.620/us-in.txt) is a FileGDB. OGR [should support it](https://pcjericks.github.io/py-gdalogr-cookbook/vector_layers.html#get-all-layers-in-an-esri-file-geodatabase) with few (if any) changes to the existing code that uses OGR to convert to CSV. We just need to include .gdb in the list of file endings to search for when considering what to send to OGR. We might also want to include a "layer" attribute in the `conform` object so we can be explicit about which GDB layer to extract.

**Comment by iandees** [comment]
Muscatine, IA is also a FileGDB: https://github.com/openaddresses/openaddresses/blob/master/sources/us-ia-muscatine.json

**Comment by iandees** [comment]
So is Harford County, MD: https://github.com/openaddresses/openaddresses/blob/master/sources/us-md-harford.json

**Comment by migurski** [comment]
Hm. Seeing this error from `gdal.VersionInfo() == '1110000'`:

    >>> ds = gdal.Open('/tmp/Streets_Address_Points_IDHS/County_Address_Points_IDHS_IN.gdb')
    ERROR 4: `/tmp/Streets_Address_Points_IDHS/County_Address_Points_IDHS_IN.gdb' not recognised as a supported file format.

But this is fine from `ogrinfo --version = GDAL 1.11.0`:

    $ ogrinfo -ro /tmp/Streets_Address_Points_IDHS/County_Address_Points_IDHS_IN.gdb
    INFO: Open of `/tmp/Streets_Address_Points_IDHS/County_Address_Points_IDHS_IN.gdb'
          using driver `OpenFileGDB' successful.
    1: County_Address_Points_IDHS_IN (Point)

I’ll investigate further.

**Comment by iandees** [comment]
FileGDB support was added in #349 .
