### ISSUE TITLE
Add time zone to runs table

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#155]
They’re all UTC now, but a lot of the code is needing to specify this and it’s bad.

**Comment by iandees** [comment]
Are you using PostgreSQL's [`datetime with timezone` data type](http://www.postgresql.org/docs/9.1/static/datatype-datetime.html) in the database? I think the Postgres client will translate it to a Python timezone-aware datetime object...

**Comment by migurski** [comment]
I’m heading in that direction. It was a mistake to define `runs` without it.
