### ISSUE TITLE
non-lowercase keys in advanced_merge

### ISSUE THREAD

**Issue by tkardi** [openaddresses/machine#176]
`conform.conform_smash_case` at https://github.com/openaddresses/machine/blob/master/openaddr/conform.py#L647-L659 is used to lowercase `conform` object keys and values. 
In case of advanced_merge the resultant *merged fieldname* (new_col) is left as it was input:
```python
>>> source = {
... 	"conform": {
... 		"city": "SomeFieldName",
... 		"advanced_merge": {
... 			"SomeFieldName" : {
... 				"separator": " ",
... 				"fields": ["THIS", "tHAT"]
... 			}
... 		}
... 	}
... }
>>> X_FIELDNAME, Y_FIELDNAME = 'A', 'B'
>>> source2 = conform_smash_case(source)
>>> source2['conform']['city']
'somefieldname'
>>> source2['conform']['advanced_merge'].keys()
['SomeFieldName']
>>> 
```

This means that if mixed- or uppercase fieldnames are used in advanced merge the corresponding values will not be found. For example as in https://github.com/openaddresses/openaddresses/pull/1117#issuecomment-127640381

**Comment by NelsonMinar** [comment]
Good report, that sounds like a real bug. I hate this case smashing stuff we do. Should be straightforward to fix, needs a proper test case in the unit tests.

**Comment by migurski** [comment]
I agree; the case-smashing makes me uncomfortable. How would you like to proceed Nelson?

**Comment by NelsonMinar** [comment]
I never did like the case smashing, but it's the way the Node code works. If we make tag naming case sensitive we will have to go through and update a bunch of source files where case doesn't match.

So I think the simple thing is just add a test for this case, then update the advanced merge code to smash the case of the newly generated column names.

**Comment by iandees** [comment]
Whenever I make a change to a source I make sure the capitalization is
correct. I'm happy continuing that. We could have the code warn us if the
case is wrong.

**Comment by tkardi** [comment]
Is the *case-smashing* there only to support case-insensitivity or is there any other reason aswell? Because in essence it works ok as much as i can see, there's just the question with advanced merge new fieldnames.

**Comment by geobrando** [comment]
advanced_merge is now deprecated and is no longer in use so this can be closed, right?

**Comment by migurski** [comment]
You’re right, I’ll close this.
