### ISSUE TITLE
Add license links to published data

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#198]

**Comment by NelsonMinar** [comment]
Implementing this would be a big step towards the license policy proposal: https://github.com/openaddresses/openaddresses-ops/issues/3

**Comment by migurski** [comment]
My current thinking is to just get the license URLs into all the outputs as a starting point.

**Comment by migurski** [comment]
PR #199 adds README.txt files to every downloadable .zip we produce, just using the existing license and website strings as a start.
