### ISSUE TITLE
Investigate trailing space in source attribution

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#201]
We are seeing some weirdness in a source, and can’t tell if the errors are transient or somehow related to a trailing space? https://github.com/openaddresses/openaddresses/pull/1214#issuecomment-137450389

**Comment by slibby** [comment]
Here's a commit that seemed to cause it to fail: https://github.com/openaddresses/openaddresses/commit/3c78625e2889e6e6f4d2bcebeaad8d87d9bee08f

I think the "failed download" is a red herring, I'll look more into where that error is raised in the code when I get a chance.

**Comment by migurski** [comment]
I can’t duplicate this. I believe the failure might actually be due to a cached result, so I’m going to close until we see it again.
