### ISSUE TITLE
Document internals

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#203]
1. Start with components.
2. Describe persistent things (S3, DB).
3. Narrate a few processes.
4. Show where AWS things come from.

![photo sep 03 5 48 59 pm](https://cloud.githubusercontent.com/assets/58730/9688092/f6f7235a-52e1-11e5-97f8-724852dc886b.jpg)

**Comment by migurski** [comment]
Getting starting in [document-internals-#203/docs](https://github.com/openaddresses/machine/tree/document-internals-%23203/docs); would love your input as I make progress @NelsonMinar.

**Comment by NelsonMinar** [comment]
Glad to help! What I'd like is to wait until you have a first draft done, then review it for clarity and completeness. If you'd rather I review an outline or earlier stuff I can do that too.

**Comment by migurski** [comment]
Great, I'll issue a PR when it's ready.
