### ISSUE TITLE
Logging: add reference to source JSON file

### ISSUE THREAD

**Issue by slibby** [openaddresses/machine#218]
It would be helpful when reviewing cache logs to know which file was being processed:

i.e. there is no way to know which .json file to view from this log: http://data.openaddresses.io.s3.amazonaws.com/runs/19217/output.txt

I believe this could be accomplished by adding 

```_L.info(u'Running cache for {}'.format(source))``` 

above this line:

https://github.com/openaddresses/machine/blob/master/openaddr/process_one.py#L40

Does that make sense? I can submit a PR if so, I don't yet have a running copy of machine on my PC to try it out.

**Comment by iandees** [comment]
I kind of did this in 2ae2430700b3455b4546d96e73fc9742d0beb78a and 924bdf179e126046732e3b98a5d70e1aacb1b731.

**Comment by migurski** [comment]
The actual names might not reach the code at that point—it’s possible they’re all just “user_input” down there, for reasons.
