### ISSUE TITLE
Populate Attribution flag 

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#230]
Second task for https://github.com/openaddresses/openaddresses-ops/issues/7: use [attribution tag](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#optional-tags) to populate a new boolean value for required attribution, and provide for explicit attribution settings by borrowing terminology from [CC namespace](https://creativecommons.org/ns). Add a True/False/Null output attribution field.

Explicit attribution requirement:

    {
        "license": {
            "attribution": true,
            "attribution name": "Joe Blow"
        }
    }

Equivalent implicit attribution:

    {
        "attribution": "Joe Blow"
    }

Missing license:attribution should be interpreted as True, so this is also equivalent:

    {
        "license": {
            "attribution name": "Joe Blow"
        }
    }

Completely omitted attribution information should be interpreted as False, equivalent to:

    {
        "license": {
            "attribution": false
        }
    }

**Comment by NelsonMinar** [comment]
Love this explicit license info. Forgive me if I missed discussion of the spec, but I had a couple of concerns here. Let me know if this commentary is at all welcome. I could try to come up with an alternate spec if it helps, it may take me a couple of days.

I'm nervous about "Completely omitted attribution information should be interpreted as False"; does that mean if some well meaning contributor forgets to include info, everyone will assume that source doesn't require attribution? I think we want a "Required / Not Required / Unknown" three state flag here (with default unknown), not just a boolean.

It also seems odd to me that "attribution" can be true/false, or also a string (your "Equivalent implicit attribution" example). 

Last comment: the CC schema includes an attributionUrl which seems like a useful thing. Should we include it?

**Comment by migurski** [comment]
Thanks Nelson, concerns welcome! I’m moving this forward in small increments exactly so that it moves forward with the right feedback.

Re: nervousness, yes. I’m thinking that right now, 100% of our sources would come through as attribution required if we didn’t do this, which smelled funny. There are 227 sources currently with `attribution` tags defined, which would mark them as required. To be clear, this works as you’re describing:

    {
        "license": { "attribution": <true/false/null> }
    }

The implied value is for this case using the [existing, soon-to-be-deprecated tag](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#optional-tags):

    {
        "attribution": <string>
    }

So it’s two places the value can come from. Does this help your nervousness, or should I change something? [Here are the current tests](https://github.com/openaddresses/machine/blob/ff93b0a5a74a49881d47f109dc783772e19bcd16/openaddr/tests/conform.py#L718) for some better detail.

Agree on the URL, just starting from there being 227 names in the existing OA data sources and not yet any URLs.

**Comment by NelsonMinar** [comment]
Thanks for the response; once again you're way ahead of me in having thought this out. As long as the `attribution` tag is planned to be deprecated we can clean this all up explicitly.

**Comment by migurski** [comment]
Great, thank you!
