### ISSUE TITLE
Listing sources missing conform

### ISSUE THREAD

**Issue by geobrando** [openaddresses/machine#233]
Did results.openaddresss.io not used to show sources missing conform objects?

Updated the license info for [us/az/glendale.json](https://github.com/openaddresses/openaddresses/blob/b15e4feadd22f9faf2b25eb1495c631560afc4e0/sources/us/az/glendale.json) and it failed hooked because of the missing conform, but it is not visible on the results page

**Comment by migurski** [comment]
Sorry for this confusion. On the front page, we make a best effort to show good data, which might mean old data. On an individual set page like the ones linked from http://results.openaddresses.io/sets/ you’ll see a synchronized few with generally fewer healthy sources.

**Comment by geobrando** [comment]
Ahh.  I see now.  Thanks!
