### ISSUE TITLE
Regex's for us/ga/*.csv is allowing bad addresses

### ISSUE THREAD

**Issue by stephenkhess** [openaddresses/machine#237]
The regexes ```^([0-9]+)( .*)``` and ```^(?:[0-9]+ )(.*)``` are applied to the STR field to extract the house number and street fields.  Unfortunately there are some source entries that are not that simple, leading to bad export entries.  Some source examples:

```
-81.61218255758295,31.445076249046316,"0 PENNICK RD BRUNSWICK 31525","glynn","ga"
-81.60793125629436,31.4285784352523,"310 VERNON LEWIS LN Unit: 54 BRUNSWICK 31525","glynn","ga"
```

and their corresponding export entries:

```
-81.5599224,31.3246046,0,Pennick Road Brunswick 31525,,,ga,,
-81.6079313,31.4285784,310,Vernon Lewis Lane Unit: 54 Brunswick 31525,,,ga,,
```

In these cases "Brunswick 31525" are the city/postalcode in GA containing those addresses.

This seems to only affect the following sources:
glynn.csv (~44491 entries)
brantley.csv (39 entries)
camden.csv (62 entries)
mcintosh.csv (7 entries)

**Comment by geobrando** [comment]
Thanks, again.  While certainly not without error, these particular regex functions were intended to be applied to number+address fields and not complete addresses. 

I will migrate this issue over to the source repo.
