### ISSUE TITLE
us/or/portland_metro.json does not export prefix and suffix directionals

### ISSUE THREAD

**Issue by stephenkhess** [openaddresses/machine#239]
Export street consists only of FNAME and FTYPE, ignoring FDPRE and FDSUF

**Comment by geobrando** [comment]
It would be helpful if you could make a pr with these additions or alternatively open an issue in openaddresses/openaddresses in case someone else might want to do it. That's a better place for source-related issues. Thanks!

**Comment by stephenkhess** [comment]
D'oh!  Sorry about that, I created the first in "machine" on the suggestion of Ian, then forgot to change projects.
