### ISSUE TITLE
Port basic conform behavior from Node implementation

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#24]
Implement [conform tags](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#conform-object) in `ConvertToCsvTask`:

* [x] Implement `type` processing tag.
* [x] Implement `number` and `street` attribute tags.
* [x] Implement `lon` and `lat` attribute tags.
* [x] Implement `merge` processing tag.
* [x] Implement `split` processing tag.

Remaining features to implement:

* [x] `advanced_merge` tag
* [x] `file` tag. `us-ca-san_mateo_county.json` is an example that needs it.
* [x] GeoJSON sources
* [x] CSV sources
* [x] csvsplit
* [x] csv encoding
* [x] csv headers
* [x] csv skiplines
* [x] csv SRS

Things with no tests:

* [x] sources that aren't ASCII
* [x] sources with an `encoding` tag
* [x] sources requiring geographic reprojection
* [x] sources with `srs` processing tag

**Comment by NelsonMinar** [comment]
Two notes on compatibility of my new Python code:

The Node conform allows field names to not match the case of the source input. That's a PITA in Python and I think unnecessary, so I'm going with case sensitive. Some source files will need to be updated to be precise about case.

The Node code has an [expand abbreviations](https://github.com/openaddresses/openaddresses-conform/blob/572b7a8066db107f028ecd5407fda0b2c7041d84/Tools/csv.js#L268) feature in it where it downcases things, renames ST to Street, etc. I have no plans to port that right now. I certainly could, but it seems like an unwise feature for the OpenAddresses product. Perhaps this question deserves its own issue for discussion.

**Comment by NelsonMinar** [comment]
Python conform code is now mostly complete for shapefile sources. It matches the behavior of the Node code pretty closely. Of the 24 sources in us-ca-* that use shapefiles 17 convert correctly.

Remaining features to implement:

*[]: `advanced_merge` tag
*[]: `file` tag. `us-ca-san_mateo_county.json` is an example that needs it.
*[]: GeoJSON sources
*[]: CSV sources, including `csvsplit`, `headers`, and `skiplines` tags.

Things with no tests:

*[]: sources that aren't ASCII
*[]: sources with an `encoding` tag
*[]: sources requiring geographic reprojection
*[]: sources with `srs` processing tag

**Comment by sbma44** [comment]
I added those features for the Korean sources, which have been languishing
in a PR, presumably because no one feels comfortable weighing in on how
Korean addressing works (I sure don't). That's where you can find the
relevant sources.

**Comment by NelsonMinar** [comment]
I believe the conform code is now feature complete, matching the docs and/or what the Node code does. There's a lot of tests, too.
