### ISSUE TITLE
KeyError: 'features' - ESRI sources

### ISSUE THREAD

**Issue by geobrando** [openaddresses/machine#242]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openaddr/process_one.py", line 54, in process
    cache_result = cache(temp_src, temp_dir, extras)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/__init__.py", line 93, in cache
    downloaded_files = task.download(source_urls, workdir)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/cache.py", line 446, in download
    resp_attrs = response.json()['features'][0]['attributes']
KeyError: 'features'
```
Affected sources:
[ca/bc/surrey.json](https://github.com/openaddresses/openaddresses/blob/c583882048336827360f4b6674a325ec5f8f5f33/sources/ca/bc/surrey.json)
[us/or/harney.json](https://github.com/openaddresses/openaddresses/blob/d75ab303fcac9f012ac18a53a4731ab38b3d1e51/sources/us/or/harney.json)
[us/az/pinal.json](https://github.com/openaddresses/openaddresses/blob/c583882048336827360f4b6674a325ec5f8f5f33/sources/us/az/pinal.json)
[us/co/city_of_arvada.json](https://github.com/openaddresses/openaddresses/blob/c583882048336827360f4b6674a325ec5f8f5f33/sources/us/co/city_of_arvada.json)
[us/ga/sumter.json](https://github.com/openaddresses/openaddresses/blob/c583882048336827360f4b6674a325ec5f8f5f33/sources/us/ga/sumter.json)
[us/il/city_of_aurora.json](https://github.com/openaddresses/openaddresses/blob/c583882048336827360f4b6674a325ec5f8f5f33/sources/us/il/city_of_aurora.json)

There are likely others.  All using Arcgis Server 10.22 and above

**Comment by geobrando** [comment]
OK. Since statistics are unable to be returned for these services there's nothing really to do. But we should keep these sources in case this is rectified. Found some evidence that this may be fixed in some circumstances with an upgrade to ArcGIS Server 10.3.1

**Comment by iandees** [comment]
I was going to ping @slibby for more ideas and maybe try to run these servers through [the ESRI node code I borrowed from](https://github.com/koopjs/featureservice/blob/master/index.js) to see how they handle this error.

I'm going to reopen this because I think we should still be able to figure out a better answer for these sources.

**Comment by geobrando** [comment]
@iandees Good call.

https://github.com/koopjs/featureservice/blob/master/index.js#L163-L177

**Comment by iandees** [comment]
Yep, that's the chunk of code I ported [to here in machine](https://github.com/openaddresses/machine/blob/bcd17a92153e46cb9172f1416e450c6b3ce769ab/openaddr/cache.py#L434-L458). I'm wondering if there's a difference because of capitalization or something.

**Comment by geobrando** [comment]
But you're not getting [here](https://github.com/openaddresses/machine/blob/bcd17a92153e46cb9172f1416e450c6b3ce769ab/openaddr/cache.py#L477-L515), which is the port the second bit of code I referenced, if you're raising an error [here](https://github.com/openaddresses/machine/blob/bcd17a92153e46cb9172f1416e450c6b3ce769ab/openaddr/cache.py#L454), right? Shouldn't you add a `continue` or refactor this and wrap it in a function? Or am I not reading this right?

**Comment by iandees** [comment]
Yea good point. I was hoping to not rely on enumerating all the object IDs as a fallback but if that's what it takes we'll have to do it!

**Comment by slibby** [comment]
Koop is by far the best example of how we've worked around scraping from different versions of Server. @dmfenton or @chelm are most intimately familiar with the workarounds that we used in that case if there are other questions.

**Comment by iandees** [comment]
I think this was fixed with better error handling code that got added to the Esri path.
