### ISSUE TITLE
Test with Pythons 2.7 and 3.3

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#26]
Whenever we get tests running in Python 3, [add `3.3` to Travis config](http://docs.travis-ci.com/user/languages/python/). Armin [suggests skipping 3.0, 3.1, and 3.2](http://lucumr.pocoo.org/2013/5/21/porting-to-python-3-redux/).

**Comment by migurski** [comment]
Figured this out in https://github.com/codeforamerica/projectmonitor/commit/d8f623e8f9e8248aceebfa3cbda7a1a5d00f894c and https://github.com/codeforamerica/projectmonitor/commit/3fa4a9960892cd7c80f3685bf6da233dadb9c2bc

**Comment by NelsonMinar** [comment]
Cool! Fair warning, a bunch of code in `conform.py` is going to take effort to make run properly in Python 3. The `unicodecsv` module should be replaced with the native `csv` module in Py3 and it has a slightly different API. Also there's an assert for Py2 buried deep in the OGR reading code because that stuff will need a close look when changing to Py3. It can all be made to work, just will require some attention.

**Comment by migurski** [comment]
I’ve been trying a bunch of different approaches to making this work in Travis so we can test with Python 3.

We rely on system-level Python packages like GDAL and Cairo, while Travis switches Python versions using virtualenv with `system-site-packages` turned off by default. Worse, the virtualenv `python` and `pip` executables in the Travis path are different from the system-level ones in `sudo`’s path called by `chef`.

I started out by taking [Armin’s Ronacher’s advice on skipping straight to 3.3](http://lucumr.pocoo.org/2013/5/21/porting-to-python-3-redux/), and experimented with a few methods for shimming a system path into the virtualenv artificially with [.pth files](https://docs.python.org/2/library/site.html):

```
install:
  - for DIR in /home/travis/virtualenv/python3*/lib/*/site-packages; do echo '/usr/lib/python3/dist-packages' >> $DIR/system.pth; echo '/usr/local/lib/python3/dist-packages' >> $DIR/system.pth; done
  - for DIR in /home/travis/virtualenv/python*/lib/*/site-packages; do echo '/usr/lib/python2.7/dist-packages' >> $DIR/system.pth; echo '/usr/local/lib/python2.7/dist-packages' >> $DIR/system.pth; done
```

This worked to a degree, but [`_gdal.so` wasn’t compatible](https://travis-ci.org/openaddresses/machine/jobs/48142155) with Python 3. I added explicit `apt-get` installations of packages like `python3-gdal`, and did the pip install from Travis directly so that packages like `future` would be accessible in the virtualenv. The [compiled `_gdal` module was no longer available](https://travis-ci.org/openaddresses/machine/jobs/48180046) at all, and I’m unsure why.

I’ve now removed the path fiddling, and switched from Python 3.3 to Python 3.2 so I can take advantage of the [explicit availability of system site packages](https://github.com/travis-ci/travis-ci/issues/2219#issuecomment-41804942) in 3.2. We are much further along, breaking on the incompatibility of `unicodecsv` with Python 3 rather than GDAL:

https://travis-ci.org/openaddresses/machine/jobs/48180760

I’m working on the `ditch-node-py3` branch and squashing certain noisy commits.

**Comment by NelsonMinar** [comment]
Nice! I know nothing about Travis. FWIW, Python 3.4.0 is what's in Ubuntu 14.4 LTR. I don't much care what version of Py3 we use. I still think there's no point in trying to keep the code working in both Python 2 and Python 3, I'd prefer to pick one. At this point, either. Totally your call.

If we want to support both versions, I think the way to go is our own 2/3 compatibility shim csv module. Mostly the code can just be a subclass of `unicodecsv` in Py2 and `csv` in Py3. But we need a bit more code to open files. Without testing, I think the main difference is code like this in Py2:
````
        with open(dest_path) as fp:
            rows = list(unicodecsv.DictReader(fp, encoding='utf-8'))
````
vs. this in Py3
````
        with open(dest_path, encoding='utf-8') as fp:
            rows = list(csv.DictReader(fp)
````

I wonder if `multiprocessing.Pool` operates significantly different in Py3? 3.2 added a [`concurrent.futures.ProcessPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html#processpoolexecutor) which is the new thing to replace that, but the old module should still be there.

**Comment by migurski** [comment]
I like the shim module idea for `csv`; I’m going to have a look at how `future` works to see if there’s anything to learn.

For the time being I would like to support both versions. Most of the world still runs on Python 2.7 and I’m prioritizing a working processor now over anything else, but I want to ensure that our tests work with both 2 and 3 for the future.

**Comment by migurski** [comment]
The [failures are getting more useful](https://travis-ci.org/openaddresses/machine/jobs/48184239) btw.

**Comment by migurski** [comment]
I’m no longer confident that 3.2 with system site packages is good enough for us. Python 3.3 is the first 3.x with 2-compatible `u''` unicode string literal syntax, and we use it everywhere with good reason. If we want to use Travis moving forward, I’m going to need to make tests work there under 3.3.

**Comment by migurski** [comment]
Tests working (though failing) [under 2.7 and 3.3](https://travis-ci.org/openaddresses/machine/builds/48212785) as of [68c152a ](https://github.com/openaddresses/machine/blob/68c152abfd959438d07c7280bdc09988f3bbdf50/.travis.yml).

**Comment by migurski** [comment]
Down to just the [intentional exceptions](https://github.com/openaddresses/machine/blob/0f5a9407df3829df33cf42e096fb8dcfb9963849/openaddr/conform.py#L348) as of https://github.com/openaddresses/machine/commit/0f5a9407df3829df33cf42e096fb8dcfb9963849.

**Comment by migurski** [comment]
[Tests passed](https://travis-ci.org/openaddresses/machine/builds/48443090) as of https://github.com/openaddresses/machine/commit/763d0a8cf9ceddb37a2c06daa91dd94b848c1ebb.

**Comment by NelsonMinar** [comment]
That was some heroic work @migurski, nicely done! Just making a note that OGR may still fail us in Python 3, due to [this bug I opened in GDAL](http://trac.osgeo.org/gdal/ticket/5811). I don't think our test suite has a test for this problem, and the only source that exhibits it is be-flanders. Lots more historical notes on this in issue #42.

I'm not optimistic about the GDAL bug process producing a fix for us. I have a theory on how to patch GDAL ourselves I can look at in a few weeks. For now, worst case we lose a source or two when running in Py3.

**Comment by migurski** [comment]
Thanks!

I think for the time being we should keep running in 2.7, and see what happens with the GDAL bug.

**Comment by NelsonMinar** [comment]
My GDAL bug was marked as fixed I few months ago. I haven't gone back and tested it myself.
