### ISSUE TITLE
Only request necessary fields when Querying Esri Services

### ISSUE THREAD

**Issue by slibby** [openaddresses/machine#268]
An idea, not sure where to implement.

For massive ArcGIS Server-backed services, there may be a significant reduction in response (and processing) time if the request only returned the fields needed for the conform object. Take NY State for example, 4M+ addresses, runs out of time caching.

Here's a request with only the necessary fields + geometry :
http://gisservices.dhses.ny.gov/arcgis/rest/services/SAM_Address_Points/MapServer/1/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=CompleteStreetName%2C+AddressNumber&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&returnTrueCurves=false&resultOffset=&resultRecordCount=&f=pjson

178ms response, 20862 bytes

Here's one with outfields=* (how machine currently runs):
http://gisservices.dhses.ny.gov/arcgis/rest/services/SAM_Address_Points/MapServer/1/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&returnTrueCurves=false&resultOffset=&resultRecordCount=&f=pjson

299 ms, 75041 byes (almost twice as long and 4x as large).

If the conform object can be loaded before caching to geojson begins, these requests could be made substantially smaller (and the resulting temp files on disk would be smaller too).

**Comment by migurski** [comment]
I like this idea. Looks like they’re just comma-delimited lists of fields that we can pull directly from the conform object.

**Comment by iandees** [comment]
I like this, too. I feel like I tried this at one point but didn't have the conform object in the right spot. That shouldn't be too hard to plumb through.
