### ISSUE TITLE
Don't apply abbreviation expansions for sources in non en-US locale

### ISSUE THREAD

**Issue by tyrasd** [openaddresses/machine#285]
In Italy, most roads are named `Via xyz` where [*via*](https://en.wiktionary.org/wiki/via#Italian) means *road* or *street* in English. The current [abbreviation expansion code](https://github.com/openaddresses/machine/blob/master/openaddr/expand.py#L214) transforms each of these to *Viaduct*. See [Firenze](https://github.com/openaddresses/openaddresses/blob/master/sources/it/52/firenze.json) [for example](http://s3.amazonaws.com/data.openaddresses.io/runs/57159/it/52/firenze.zip).

As the expansion code is only intended for [US English](https://github.com/openaddresses/machine/blob/master/openaddr/expand.py#L2) abbreviations, it doesn't make sense to apply it to sources outside the US.

**Comment by iandees** [comment]
We're [pulling out the renaming/expanding stuff completely](https://github.com/openaddresses/machine/pull/281), just waiting for comment from downstream users.

**Comment by migurski** [comment]
I’ll be merging #281 now, and will address this issue by further turning off expansion for non-US addresses in collections.

**Comment by riordan** [comment]
Hooray!
