### ISSUE TITLE
Debugging aid: better logging config

### ISSUE THREAD

**Issue by NelsonMinar** [openaddresses/machine#29]
The logging config is about 75% of the way to being useful. Here's a proposal to make it excellent. [This article on logging practices](http://victorlin.me/posts/2012/08/26/good-logging-practice-in-python) has useful contextual advice.

1. Code should log to a logger obtained via `logger.getLogger(\_\_NAME__)`. This results in loggers being named hierarchically after code modules, like `openaddr.conform`. With that naming scheme, logging levels can be configured on a per-module basis.
2. Each module should instantiate the logger once, at the top, via `_L = logger.getLogger(__NAME__)`. That way normal code can just do `_L.debug("foo")`. Note that the logging config has to set `'disable_existing_loggers': False` for this style to work right, see the linked article for details. I'm not wedded to the name `_L`, but I'd like it to be short.
3. There should be a logging setup utility method all the various main() entry points to our code shares. The default behavior is to log warning and above to stderr.
4. The default should be overrideable with a YAML file named `$HOME/.openaddr-machine-logging`, or pointed to by an `OPENADDR_MACHINE_LOGGING` environment variable. 
5. Tests should not log to stderr by default. Maybe make logs write to a file in /tmp that's not deleted if a test fails? Or just rely on the file config for debugging.
6. Mike proposed command line switches like `--verbose` to change the log level. That sounds nice, not sure how it interacts with the YAML file.

**Comment by migurski** [comment]
My thinking with `--verbose` and `--quiet` is that it tweaks the logging level from the default. Defaults would be _DEBUG_ for “main” things like top-level functions, and _INFO_ for “task” things like caching or conforming. `--verbose` would dial everything to _DEBUG_, while `--quiet` would turn the first down to _INFO_ and the second down to _WARN_.

I’m not sure this quite interacts with the use of `__name__` for setting up logger; the module layout doesn't exactly map to how high-level a task. Hope this makes sense.

**Comment by NelsonMinar** [comment]
I've committed the majority of my proposed changes to ditch-node. I'll implement the rest tomorrow unless you don't like the way it looks.

Below is a sample

**Comment by NelsonMinar** [comment]
I've committed the majority of my proposed changes. Take a look? I'll finish the work tomorrow unless I hear someone say they don't like the way this works.

The only functional change at the moment is that if you have a ~/.openaddr-logging.json file it will be used to configure logging. Otherwise the same old stderr + optional logfile config is used.

Here's a sample config. I'm not in love with using JSON for config files but it seemed better than adding a YAML dependency.

````
{
    "version": 1,
    "disable_existing_loggers": false,
    "formatters": {
        "simple": {
            "format": "%(relativeCreated)7d %(levelname)06s %(module)12s:%(lineno)-4d %(message)s"
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "DEBUG",
            "formatter": "simple",
            "stream": "ext://sys.stderr"
        }
    },
    "root": {
        "level": "DEBUG",
        "handlers": ["console"]
    },
    "loggers": {
        "openaddr": { "level": "INFO" },
        "openaddr.conform": { "level": "DEBUG" },
        "requests": { "level": "ERROR" }
    }
}
````

**Comment by NelsonMinar** [comment]
This is now implemented. WARNING is now the default log level and everything is much quieter. I hereby volunteer to show any and all comers how to use the log config JSON file to full effect, it's very handy once you get the knack of it.
