### ISSUE TITLE
duplicate entries in global.zip?

### ISSUE THREAD

**Issue by maxogden** [openaddresses/machine#292]
hello friends,

when I do `unzip openaddr-collected-global.zip` I get this:

```
inflating: ../openaddresses/us/mt/lake.vrt  
inflating: ../openaddresses/us/mt/lake.csv  
replace ../openaddresses/us/mt/lake.vrt? [y]es, [n]o, [A]ll, [N]one, [r]ename: 
```

it looks like there are two entries in the zip with the same filename? there are a few of these actually. do you think this is actually a bug?

**Comment by migurski** [comment]
Weird! This sounds like a bug, I will investigate.

**Comment by maxogden** [comment]
i parsed the zip entries and there are all the dupes:

```
      2 us/ia/clarke.csv
      2 us/ia/clarke.vrt
      2 us/ia/sioux.csv
      2 us/ia/sioux.vrt
      2 us/mt/lake.csv
      2 us/mt/lake.vrt
```

**Comment by maxogden** [comment]
looks like a conspiracy around the land of 1000 lakes. they must be hiding something

**Comment by migurski** [comment]
![lakes](https://cloud.githubusercontent.com/assets/58730/12804949/8f6311ac-caac-11e5-8cd2-59e39464caaa.jpg)
