### ISSUE TITLE
Permanent URLs for most recent version of products

### ISSUE THREAD

**Issue by NelsonMinar** [openaddresses/machine#293]
There are currently no stable URLs for the most recent version of individual source outputs. Ie right now this is the latest Chicago result:
  http://s3.amazonaws.com/data.openaddresses.io/runs/58957/us/il/city_of_chicago.zip
but the only way to find that artisanal integer 58957 is to parse http://results.openaddresses.io/state.txt

In Slack we discussed this and the consensus proposal was to serve this on results.openaddresses.io, with a URL like 
 http://results.openaddresses.io/latest/us/il/city_of_chicago.zip

I think it's sufficient to serve a 302 redirect from that URL to whatever S3 URL actually has the data file at the moment.

**Comment by migurski** [comment]
I went with http://results.openaddresses.io/latest/run/us/il/city_of_chicago.zip, since we already have [one other thing under the `/latest` path](http://results.openaddresses.io/latest/set).
