### ISSUE TITLE
support ftp download

### ISSUE THREAD

**Issue by NelsonMinar** [openaddresses/machine#30]
us-ca-placer-county is an FTP source, but the code doesn't work with FTP. Looks like the requests library doesn't do FTP. Here's [one dubious-looking solution](https://pypi.python.org/pypi/requests-ftp), may be easier just to fall back to stock python FTP.

````
I    cache:124  Requesting ftp://ftp1.placer.ca.gov/cdra/gis/parcel_point_ByAddress.zip
Process oa-cache-us-ca-placer_county:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nelson/src/oa/openaddresses-machine/openaddr/__init__.py", line 84, in thread_work
    downloaded_files = task.download(source_urls, workdir)
  File "/home/nelson/src/oa/openaddresses-machine/openaddr/cache.py", line 130, in download
    raise DownloadError("Could not connect to URL", e)
DownloadError: ('Could not connect to URL', InvalidSchema(u"No connection adapters were found for 'ftp://ftp1.placer.ca.gov/cdra/gis/parcel_point_ByAddress.zip'",))
````

**Comment by iandees** [comment]
Ah, now I remember that this is why I was using `urllib2` originally :). I think `requests-ftp` should work OK for now.

**Comment by migurski** [comment]
How does `requests-ftp` work with `httmock`?

**Comment by migurski** [comment]
Seemingly not well, might require some extra work to make test mocks work, but we can work with that.

**Comment by NelsonMinar** [comment]
I just gave requests-ftp a try and it does work with as simple a change as
  `requests_ftp.monkeypatch_session()`
I can commit a small change and close this ticket. That being said the docs sure don't give me a happy feeling. "cowboyed together in about 4 hours of total work, has no tests, and relies on a few ugly hacks".

The alternative is to have `cache.py` have a separate code path for FTP sources that uses `urllib2` or `ftplib` to make the download. I think we should stick with requests for HTTP; it's a much better library. Right now `cache.py` doesn't even check if it needs to do a download or if there's a local copy that's up to date. When we add that code I sure don't want to be doing it in `urllib2`.

Is `httmock` support essential? Not much point making a special FTP test if we're going to mock out the network transport anyway.

**Comment by NelsonMinar** [comment]
I've gone ahead and committed a change to use requests-ftp. If it proves inadequate we can easily take it out later. Mike, let me know if you need help figuring out `httmock` issues.
