### ISSUE TITLE
Error parsing CSV

### ISSUE THREAD

**Issue by trescube** [openaddresses/machine#315]
In the source [sources/us/or/portland.json](https://github.com/trescube/openaddresses/blob/add-units-to-or/sources/us/or/portland.json), it appears that the CSV parser is not recovering from an error caused by an invalid line in the source data file.  Here's the [log output](http://s3.amazonaws.com/data.openaddresses.io/runs/67788/output.txt).  The error is:

`Error in row 145573: 'NoneType' object has no attribute 'replace'`

The error is referring to the line:

`"475756","2211","2211","","SE","OCHOCO","ST","",""","PORTLAND","MULTNOMAH","OR","97222","","2211 SE OCHOCO ST #"","7652570.116","660713.526"`

Note the 9th field value `"""`.  Also note that 15th field contains a spurious `"`: `"2211 SE OCHOCO ST #""`.  

This appears to be an error in the data file since the line immediately preceding it has a 9th field value `""`:

`"621987","2211","2211","","SE","HUDSON","CT","","","TROUTDALE","MULTNOMAH","OR","97060","2312","2211 SE HUDSON CT","7720781.402","683291.251"`

This line is processed without known error.

**Comment by trescube** [comment]
I looked at the code and the problem appears to be here:

https://github.com/openaddresses/machine/blob/master/openaddr/conform.py#L704-L715

The us/or/portland.json source is a CSV file with `X` and `Y` as the last two fields.  Row #145573 contains 2 spurious `"`s which causes it to be parseable as CSV, but incorrectly and with an incorrect number of fields and therefore no `X` and `Y` fields.  The code referenced above assumes that the fields are there and throws an exception when no value is found.  This catches it, then percolates the exception up the stack:

https://github.com/openaddresses/machine/blob/master/openaddr/conform.py#L669-L671

I imagine that this is probably acceptable behavior since the standard error case is that the source CSV simply doesn't contain an `X` or `Y` field so why bother logging 416,426 errors when 1 is sufficient, but in this special case only a single line is in error while the rest of the file is parseable good data.

**Comment by NelsonMinar** [comment]
Thanks for chasing this down! The code should be smarter about the case where a single row is missing X or Y. Should be a simple enough fix. Note that the file is a well formed CSV, of sorts, in that the quotes are balanced. Just this one row means something unexpected when parsed.

**Comment by trescube** [comment]
I sent an email describing the problem so hopefully they can fix at the source.
