### ISSUE TITLE
sample excerpts don't work on Japanese CSV

### ISSUE THREAD

**Issue by NelsonMinar** [openaddresses/machine#35]
With 15387dc3a8 the conform code now can handle the Japanese CSV sources like jp-nara.json. `process_one` fails when trying to write `sample.json`:
` UnicodeDecodeError: 'utf8' codec can't decode byte 0x93 in position 0: invalid start byte`
My guess is what's going on is the `excerpt()` function uses OGR to read all sources, but the OGR code can only read UTF-8. The Japanese CSV inputs are in a Shift-JIS variant.

@migurski do you have time to look at this or should I? I suspect the sampler will need to read a bunch of the CSV processing tags in order to sample correctly as a dictionary. Maybe it'd be easier just to publish the first 10 lines of the CSV file as a CSV sample. The conform code has a lot of CSV reading code, see `csv_source_to_csv()`. Unfortunately it also does some processing on the CSV that's not appropriate for sampling.

**Comment by migurski** [comment]
I’m hearing support for switching to Fiona to deal with this over in https://github.com/openaddresses/machine/issues/42.

**Comment by NelsonMinar** [comment]
I don't think Fiona will help with this problem. The Python code does not use OGR to read CSV sources, it's got special CSV parsing to handle non-UTF-8 CSV sources, badly formed CSV, etc. I think the sampler code needs to share that CSV parsing to sample correctly.

(The Python CSV code does use OGR strictly to protect the lat/lon Point from the CSV to an output lat/lon, but that's very low level projection math, not CSV processing nor encoding.)

**Comment by NelsonMinar** [comment]
I don't think Fiona will help with this problem. The Python conform code does not use OGR to read CSV sources, it's got special CSV parsing to handle non-UTF-8 CSV sources, badly formed CSV, etc. I think the sampler code needs to share that CSV parsing to sample correctly. Alternately, we could just define CSV sampling to be "present the top 10 rows in the file" and call it a day.

(The Python CSV conform code does use OGR strictly to project the lat/lon Point from the CSV to an output lat/lon, but that's very low level projection math, not CSV processing nor encoding.)

**Comment by migurski** [comment]
I believe that the commit above may have fixed this issue; it works on the `jp-nara` source in `tests/conforms`. What test can we add to make sure?

**Comment by NelsonMinar** [comment]
I agree e5099e5 fixes the sample problem. Thanks! I just reran all 71 jp- and kr- sources and the output looks great; out.csv and sample.json both have valid Japanese or Korean characters. I'll close the issue.

I keep forgetting that the Sample code and the Conform code have entirely different ways of reading the source input. Sample does its best to read everything through OGR. Conform reads Shapefiles, GeoJSON, and GML through OGR but uses its own code for CSV. I kind of like having two different methods, but I need to keep it straight when reasoning about what code is doing what.
