### ISSUE TITLE
Store checksum of processed file in state.txt

### ISSUE THREAD

**Issue by orangejulius** [openaddresses/machine#372]
@avfulson17 and I were recently using [state file](http://results.openaddresses.io/state.txt) to build a downloader script for https://github.com/pelias/openaddresses, and we hoped to use the `fingerprint` field to determine whether a previously downloaded copy of an individual zip was up to date and fully downloaded.

After a little debugging we realized that the `fingerprint` field is the md5sum for the input data, not the output zip. It would be great to also have a checksum for the output of each run.

**Comment by migurski** [comment]
You're thinking you'd like to determine whether you need to process a file at all, yes? This might also help us understand whether files are falling out of date.

**Comment by iandees** [comment]
Rather than storing a checksum, might it be better to store the "finished processing" timestamp? That would solve the "should I update this source" question and answer the "how old is this data" question.

**Comment by iandees** [comment]
(Or...both 😄 )

**Comment by migurski** [comment]
Yeah! A thing that's interesting to me about the checksum is that we are storing a ton of duplicate data in S3, and maybe we should use content hashes to do less of that, with the side benefit of signaling to downstream users about the freshness of data.

**Comment by iandees** [comment]
Oh, speaking of S3: we do get free MD5 hashes when we finish uploading to S3 (they populate an ETag header, I think).

**Comment by orangejulius** [comment]
Timestamps are okay, but checksums solve both the "is this file up to date?" and "is this file somehow corrupt? (from an incomplete download, network issues, disk issues, or anything else)" with one go, so they're much more interesting to me. Might it be that S3 already sends the checksum in the _response_ headers when we download the files?

**Comment by migurski** [comment]
Each run of each source places the zip file in a new path, under `/runs/{id}/{source}.zip`. The path would need to become something different, like `/runs/{hash}/{source}.zip`.

**Comment by migurski** [comment]
Circling back, @orangejulius would it be sufficient for you if we ensured that URLs for new content were unique, and the `Last-Modified` header was correct?

**Comment by orangejulius** [comment]
If the hash is in the URL, then that's totally fine. Last-Modified headers are nice, but a hash is the key that allows checking for both corruption and being up to date. Oh and to be clear, there's no rush, but when it happens it will be excellent!

**Comment by migurski** [comment]
Can you say more about how you would use it to look for corruption?

**Comment by orangejulius** [comment]
Sure! So to be clear this is not to validate that the file as stored on S3 is corrupt in some way, but simply to ensure that the version that someone downloads is identical to the one on S3. Like I said there are of course many ways during downloading and storing the data that errors can crop up. In particular, S3 in my experience is very happy to return partial content responses, especially if there happens to be a significant amount of traffic at that moment. Its true you can use the content-length to check for this, but its still annoying.

Assuming no one is [being deliberately evil](http://www.mscs.dal.ca/~selinger/md5collision/), even an md5 hash has an overwhelming probability of being unique so files with matching checksums are likely to be the same. 

The procedure I want to implement for downloading all the files for pelias is something like this.

0.) A download directory already exists, and already contains zip files from previous runs which may be a week or more old.
1.) Check each entry in the `state.txt` file: if a file with that filename and hash exist, continue to the next. Otherwise, remove any file with that name and redownload. Check the newly downloaded file against the hash again, to verify it's correct. Possibly, repeat this some bounded number of times if the file continues to be corrupt.
2.) Extract all the zip files to a working directory and import them into pelias.

Even with content lengths and last modified headers, its possible for data errors to sneak through. With a hash, its possible to be confident that the file downloaded is not corrupt without checking anything else!

**Comment by migurski** [comment]
Would it still serve your needs, if we were to put that content hash into a response header like `X-Amz-Meta-Content-Hash` instead of the `state.txt` file?

**Comment by migurski** [comment]
I don’t think the ETag header is suitable for this, by the way. Amazon’s docs say that “ETag may or may not be an MD5 digest of the object data,” so I don’t think it’s reliable to interpret it that way.

**Comment by NelsonMinar** [comment]
My gut feeling is it's better to use our own special `state.txt` mechanism, not HTTP headers. `ETag` would be the right header but it has never worked reliably in HTTP, it's poorly defined.

**Comment by orangejulius** [comment]
I would definitely prefer it to be in the `state.txt` file, otherwise there's the complexity of managing a `HEAD` request to every URL in the list. But as long as the checksums exist and are available, it's fine.

**Comment by migurski** [comment]
Okay!

**Comment by migurski** [comment]
There is now a `process hash` column in http://results.openaddresses.io/state.txt. It’ll be empty for any output created prior to machine 2.28.0.
