### ISSUE TITLE
500 from /latest/run endpoint with non-ASCII filenames 

### ISSUE THREAD

**Issue by thatdatabaseguy** [openaddresses/machine#381]
Hey all - attempting to use the /latest/run endpoint (thanks for adding said endpoint, quite useful!) from results.openaddresses.io to download the latest copies of a number of whitelisted files on a periodic basis.

I'm getting a few 500s from the server for filenames that have non-ASCII characters in the name. Here are a few forms of a URL that will reproduce the issue:
- UTF-8 encoded: http://results.openaddresses.io/latest/run/fi/etelä-karjala-fi.zip
- Percent-encoded: http://results.openaddresses.io/latest/run/fi/etel%C3%A4-karjala-fi.zip
- Percent-encoded and NFD normalized: http://results.openaddresses.io/latest/run/fi/etela%CC%88-karjala-fi.zip

It looks like [this method](https://github.com/openaddresses/machine/blob/master/openaddr/ci/webhooks.py#L222) is where the exception occurs. I'd guess it probably has something to do with encoding, though a traceback from the logs would certainly elucidate if anyone's got one handy.

**Comment by migurski** [comment]
Thanks for reporting this — I’ve seen behavior like this in the past, and ended up doing what I think may have been percent-encoded UTF8? I’ll investigate and attempt to fix.

**Comment by migurski** [comment]
In 2.34.1, these paths now seem to work. I am seeing different behavior between my browser and curl, so there's still something shonky about unicode handling. Can you confirm from your end?

**Comment by migurski** [comment]
I can no longer duplicate this error; closing.

**Comment by thatdatabaseguy** [comment]
Oh, forgot about this, but yes - working here too.
