### ISSUE TITLE
Add the ability to upload to S3 via machine

### ISSUE THREAD

**Issue by iandees** [openaddresses/machine#414]
In https://github.com/openaddresses/openaddresses/pull/2086, @migurski suggested that we could add support to machine to upload data to our S3 cache bucket. The interesting bit would be to control access to upload via GitHub authentication.

**Comment by iandees** [comment]
@migurski are you thinking a web file upload thing or a command-line tool upload thing?

**Comment by iandees** [comment]
I remembered making this form on Wufoo (which includes an upload form element):

https://osmus.wufoo.com/forms/open-addresses-data-donation/

**Comment by migurski** [comment]
I’m thinking this would be a web file upload, with a unique directory prefix determined by the machine. Github auth [is already a thing](http://results.openaddresses.io/auth), added and then back-burnered as part of https://github.com/openaddresses/machine/issues/378.

**Comment by migurski** [comment]
And yeah, using the S3 POST API we can push files directly to S3 with a callback. That should provide enough for an org member to get a thing into the right place in the data bucket, and then use the resulting URL in a source file.

**Comment by iandees** [comment]
Yea, sounds good to me.

**Comment by migurski** [comment]
This now works, here: https://results.openaddresses.io/upload-cache
