### ISSUE TITLE
The Upload Form Didn’t Work

### ISSUE THREAD

**Issue by trescube** [openaddresses/machine#417]
I navigated to https://results.openaddresses.io/upload-cache, clicked the LOG IN button, was redirected to github for authorization, clicked Authorize Application, and was redirected back to https://results.openaddresses.io/upload-cache.  It still presents me with a LOG IN button but clicking on it does nothing (thought it presumably forwards to github, then back).

**Comment by migurski** [comment]
When you got redirected back, there are some additional params that Github adds to the URL. What are they?

**Comment by trescube** [comment]
I get redirected back to (at least I think it's a redirect) https://results.openaddresses.io/upload-cache but here are the calls being made:

<img width="834" alt="screen shot 2016-10-26 at 10 37 32 am" src="https://cloud.githubusercontent.com/assets/658991/19730489/65252a6e-9b68-11e6-9c5f-378bdc62258c.png">

**Comment by migurski** [comment]
What's at the end of the callback there? Any way to get those values?

**Comment by trescube** [comment]
https://results.openaddresses.io/auth/callback?code=1057af44c556d7b11e4e&state=eyJ1cmwiOiJodHRwczovL3Jlc3VsdHMub3BlbmFkZHJlc3Nlcy5pby91cGxvYWQtY2FjaGUifQ.tvyFWgQT_gwcMIDc1iS0w-4HEdE

**Comment by migurski** [comment]
Hm, it looks like a legit callback, but Github thinks it might be an unlegit code. If you don't mind, I'll follow up privately to see if I can remote-debug this as you do it.

**Comment by trescube** [comment]
Sure, sounds good.

**Comment by migurski** [comment]
We determined that private org membership was an issue, so I added `org:read` scope to OAuth and a hopefully-helpful message about what failed.
