### ISSUE TITLE
ogr_source_to_csv() doesn't support encodings

### ISSUE THREAD

**Issue by NelsonMinar** [openaddresses/machine#42]
Do the OGR Python bindings support a way to identify the source encoding? @iandees or @migurski do you know? Maybe @sgillies?

The source `be-flanders` is a shapefile in ISO-8859-1 (even if the source JSON doesn't say so yet) and isn't converting to Unicode correctly. As far as I can tell our code in `ogr_source_to_csv()` doesn't have any provision for dealing with source encodings. So far we haven't had any problems, but I'm wondering if we've just gotten lucky and most shapefiles are in UTF-8.

I can't find an OGR API for specifying the source encoding but I don't really understand OGR. Setting the environment variable `SHAPE_ENCODING` does seem to work but that's awfully hacky and might break if we multi-thread.

If OGR can't be made to do the conversion when reading the file, the other option would be to treat OGR's output as byte strings and decode to Unicode ourselves. A quick glance suggests that's what Fiona does. But I don't know OGR well enough to just charge in and do it.

For a specific test example, in the be-flanders shapefile there's a row with longitude 3.7097669529002757 early on that contains a non-ascii street name. That row in the projected, extracted CSV (with the 0xEF byte that marks this as not valid UTF-8) is 2000000686.0,70984.0,Ma[EF]sstraat,90,,,90,44021,Gent,9000,manueleAanduidingVanPerceel,3.7097669529002757,51.07133310993189

**Comment by migurski** [comment]
In my experience, the hacky environment variable is how OGR chooses to solve this class of problem. It’s gross but seems to be part of the project culture.

**Comment by NelsonMinar** [comment]
Environment variables, ugh. I believe `jobs.py` uses threads already, right? Threads share the environment. We could fork a process just for using OGR but that's dumb, I think I might prefer just converting the strings ourself. If that's possible, really need to understand OGR/Python's approach to Unicode.

**Comment by sgillies** [comment]
@NelsonMinar OGR does a fair job at detecting encodings since 1.9 but doesn't have a method for getting the detected encoding in 1.11. It might in 2.0. 

I typed up some notes about how I'm making Fiona work with OGR's support for UTF-8 everywhere since 1.9 at https://github.com/Toblerity/Fiona/blob/master/docs/encoding.txt. It might be of some help. I feel like Fiona is more reliable with encodings than OGR's Python bindings are, but there are still a lot of rough spots, eg Shapefiles in encodings other than ISO-8859-1.

**Comment by NelsonMinar** [comment]
Thanks @sgillies. I'm still confused as to what the strings returned by the Python OGR bindings are. Is the Python type unicode or bytes? And when is the source content properly decoded? Hearing that OGR is trying to guess at the encoding makes me nervous. I think I need to spend some time reading sources, both the Python OGR binding code and Fiona.

Unwinding this is a good argument for using Fiona, since it already solved the problem. But we started with some mostly-working Python OGR code so I want to stick with it for now.

**Comment by sgillies** [comment]
I've been away from ogr.py for a while, but I think the methods (like `GetField()` and `SetField()`) deal in UTF-8 byte strings. That's what I read in http://lists.osgeo.org/pipermail/gdal-dev/2012-April/032391.html.

**Comment by NelsonMinar** [comment]
Two possible sources of test shapefiles: [Fiona](https://github.com/Toblerity/Fiona/tree/master/tests/data) and Mike Bostock's [Javascript shapefile library](https://github.com/mbostock/shapefile/tree/master/test).

**Comment by iandees** [comment]
The stuff we're doing with OGR is really basic iteration over features with a reprojection. This sort of thing must be easier on Fiona. If it also buys us better encoding support and doesn't lose any support for sources we should probably prioritize switching over.

**Comment by migurski** [comment]
I looked in Fiona, and found a relatively small amount of code that implements this logic. @sgillies I'd love your eyes on [e5099e5](https://github.com/openaddresses/machine/commit/e5099e5a23b8ab6571227c5f8487034c8a8b7cc2), [especially `guess_source_encoding()`](https://github.com/openaddresses/machine/blob/e5099e5a23b8ab6571227c5f8487034c8a8b7cc2/openaddr/conform.py#L213). Am I interpreting Fiona right?

I think this allows us to coast a little longer without switching libraries.

**Comment by sgillies** [comment]
@migurski I think that's close. It doesn't account for non standard Shapefiles that are other than ISO-8859-1, which is what I'm doing at https://github.com/Toblerity/Fiona/blob/master/fiona/ogrext.pyx#L382: if you know that your Shapefile has UTF-8 attributes you can do `with fiona.open(file.shp, encoding='UTF-8') as src: ...` otherwise Fiona presumes ISO-8859-1.

**Comment by migurski** [comment]
Ah, where does that userencoding come from? I thought that `OGR_DETECTED_ENCODING` might be a hint, but I can’t see it used anywhere in the library.

**Comment by sgillies** [comment]
it comes in through the encoding keyword arg to `fiona.open`.

In Fiona, `OGR_DETECTED_ENCODING` is just a placeholder for the detected encoding that the OGR library will on day provide us.

**Comment by NelsonMinar** [comment]
I think [guess_source_encoding()](https://github.com/openaddresses/machine/blob/e5099e5a23b8ab6571227c5f8487034c8a8b7cc2/openaddr/conform.py#L213) may help conform handle Shapefiles in various encodings. I'm getting a little lost; I hope to assemble a simple set of test shapefiles to ensure we're doing this exactly right. Right now I have no idea what encoding the shapefiles we've been using are in, nor really what OGR/Python is doing when presenting them to us.

We may only have one non-UTF-8 shapefile in the source list, be-flanders. (I tagged that ISO-8859-1 myself because that's what it looks like on inspection.) There are a few other non-US shapefiles that are processing in our code without any errors. be-wa-brussels-fr, be-wa-brussels-nl, and ca-qc-gatineau all produce an out.csv with non-ASCII characters. it-er-rimini and za-nl-ethekwini both produce purely ASCII out.csv files. All the non-Latin sources are CSV files and so aren't using OGR to conform.

**Comment by NelsonMinar** [comment]
I spent a lot of time looking at this today, very detailed notes with sample inputs [on my blog](https://nelsonslog.wordpress.com/2015/01/15/ogrpython-vs-unicode/). It appears OGR's `getField()` mostly returns UTF-8 byte strings in Python2 and Unicode strings in Python3, as it should. That's why most sources work. But with `be-flanders`, OGR is returning ISO-8859-1 byte strings in Python2 and throws an Exception in Python3. Either OGR has a bug or this shapefile is corrupt. Without help from someone expert in OGR I can't get any further.

We only have one example source that triggers this problem. I'm inclined to just close this WILLNOTFIX. Alternately I could make `be-flanders` work in Python 2 fairly painlessly (following Sean and Mike's lead with `guess_source_encoding()`) but I'm not confident the fix is really correct and it will fail in Python 3.

**Comment by migurski** [comment]
If we add an explicit `encoding` tag to the Flanders source, does that fix it? If yes, and if this failure produces a meaningful error output in the log, then I think this issue is closeable.

**Comment by NelsonMinar** [comment]
We have no code to use `encoding` tags, and FWIW I added it to `be-flanders` already. What I'm saying here is I'm not quite sure how to write code to use that tag. In Python2 if OLCStringsAsUTF8 is False then I think we can decode according to the encoding that's in the source file, that's about what you did in #35 for excerpts for CSV files using OGR. But I'm only 85% sure that's correct. And Python3 OGR just throws Exceptions with this kind of input, nothing we can do about it.

I should probably just add the code and not worry about it being broken in Python3, but it bugs me. Maybe I should file a bug with OGR but I don't know those developers well enough to do that effectively.

**Comment by migurski** [comment]
Should we add support for the encoding tags similar to https://github.com/openaddresses/machine/commit/e5099e5a23b8ab6571227c5f8487034c8a8b7cc2? It seemed to work with excerpts from `jp-nara` so we could add to the conform?

**Comment by NelsonMinar** [comment]
I don't think the approach in e5099e5 will work in Python 3. I think that approach will work in Python 2, that's the thing I'm 85% sure about. I'm trying extra-hard to do this carefully.

**Comment by NelsonMinar** [comment]
I did some testing with Fiona and it's able to open both sources in both Python 2 and 3, and decodes to Unicode correctly all the time. Details [on my blog](https://nelsonslog.wordpress.com/2015/01/15/fiona-vs-unicode/).

Looking at this more closely I think in Python 2 OGR doesn't try to decode at all. Which makes sense, since it's returning byte strings. I can work with that. Can't do much about that Python 3 exception though, I plan to file a bug report.

**Comment by NelsonMinar** [comment]
**Summary of what I learned**.

In Python 2, OGR returns byte sequences for text. If OGR was able to guess the source encoding, then `OLCStringsAsUTF8` is set and the byte sequence is a UTF-8 encoded string. If OGR was not able to guess then the byte string is whatever encoding was in the source file. In either case, this code now explicitly decodes the OGR byte string to a Python Unicode string. That then gets encoded to UTF-8 and written to the extraction CSV.

I tested this by hand against all known non-ASCII sources and it works. We now have `be-flanders`! I don't know how to produce small shapefiles for a test suite. I'd love two small test files: one shapefile in UTF-8 where OGR can guess the encoding (like `ca-qc-gatineau`), and one shapefile in ISO-8859-1 where it can't (like `be-flanders`).

**Comment by NelsonMinar** [comment]
I've filed a bug on GDAL: http://trac.osgeo.org/gdal/ticket/5811

I'm closing this ticket, but if anyone still has opinions about this stuff feel free to chime in and/or reopen it.

**Comment by NelsonMinar** [comment]
Somewhat related, Sean filed an issue on Fiona to clarify the docs about how it handles a user-supplied encoding in the Open call. Basically it's only used for writing files, not reading them. https://github.com/Toblerity/Fiona/issues/197

**Comment by NelsonMinar** [comment]
The GDAL bug I filed has been closed with a patch: see [comment here](http://trac.osgeo.org/gdal/ticket/5811#comment:3).

**Comment by migurski** [comment]
Looks like it’s slated for release in GDAL 2.0.
