### ISSUE TITLE
FTP Cacher Python Issue?

### ISSUE THREAD

**Issue by iandees** [openaddresses/machine#422]
See stack traces in:

http://s3.amazonaws.com/data.openaddresses.io/runs/123339/output.txt

**Comment by migurski** [comment]
Yuck, that's a Python 3 issue, possibly with old Requests-FTP.

**Comment by migurski** [comment]
Looking good:

![preview](https://cloud.githubusercontent.com/assets/58730/20040927/6dea5fba-a415-11e6-9093-04915d63a77b.png)

**Comment by iandees** [comment]
👍
