### ISSUE TITLE
openaddr-process needs source-aware log streams

### ISSUE THREAD

**Issue by NelsonMinar** [openaddresses/machine#43]
When processing a source fails, we'd like to present the debug logs from the program to the user on the dashboard at http://data.openaddresses.io/. So our code needs a way to collect per-source logs. openaddr-process is managing the jobs, using Python threads to run things in parallel. So really we need a per-Thread way to sort out logs.

Mike and I talked and we think the way to do this is to install a special `logging.Handler` in the Thread manager in `jobs.py`. It will intercept logging messages from the entire Python process and then identify which source the message came from based on the thread ID or thread name in the `LogRecord`. It can then use its own `logger.Formatter` to write them to a per-source output file. This apparatus runs alongside any other debug logs, we think all the code can be isolated in `jobs.py`.

Other ideas we discussed: having every `Logging.debug()` call include a keyword, generating new logger objects for each source, leveraging Thread-local variables somehow. The Java library log4j's [Thread Context](http://logging.apache.org/log4j/2.x/manual/thread-context.html) abstraction would be useful, but the Python library doesn't have anything like that. But we think the `LogRecord`'s thread data will work best.

PS: `logging` is [explicitly designed](https://docs.python.org/2/library/logging.html#thread-safety) to be thread-safe. We don't use `multiprocessing`, but if we do it's more complicated [how it interacts with logging](https://docs.python.org/2/library/multiprocessing.html?highlight=multiprocessing#logging).

**Comment by migurski** [comment]
The ideal place to do this would be [in jobs.py](https://github.com/openaddresses/machine/blob/ce9f1f5d3b5aef692686f542936e86864f971e9f/openaddr/jobs.py#L61), where `process_one.process()` returns. That’s tricky because the return value there is a path to a JSON file, whose `output` value would need to be replaced. It’s set [in `process_one.write_state()`](https://github.com/openaddresses/machine/blob/ce9f1f5d3b5aef692686f542936e86864f971e9f/openaddr/process_one.py#L78), pretty deep down looking for `output.txt` which we know doesn’t exist in this version. It may be useful to refactor `process()` so that it returns a result object like [conform](https://github.com/openaddresses/machine/blob/ce9f1f5d3b5aef692686f542936e86864f971e9f/openaddr/conform.py#L50) and [cache](https://github.com/openaddresses/machine/blob/ce9f1f5d3b5aef692686f542936e86864f971e9f/openaddr/cache.py#L34) instead of a file path.

**Comment by NelsonMinar** [comment]
I made a demo of a program that logs each thread's stream to a separate file: https://gist.github.com/NelsonMinar/74d94f8bcb78fae150e3

The `MultiHandler` class there should be reusable, just drop it in to the multi-threaded processor and adjust it to write to the file you want. I've set it up to key the filename off the Thread name, but you could also use any thread local variable. Or open the output file in the same place that creates the Threads, store the open file pointer in a thread local.

**Comment by migurski** [comment]
The single handler that fans out might be duplicative of internal features from `logging`. I tried an alternative version that relies on adding filtered handlers to the `openaddr` logger, streaming the results to a buffer:

https://gist.github.com/migurski/e73faf00d7e1c5e44bd6

It would go in [jobs.py `_run_process_one()`](https://github.com/openaddresses/machine/blob/3dd1f461875d95e74651e40ce93d47139f6cb91a/openaddr/jobs.py#L41). What do you think? It's a fairly different approach, but there’s less overriding of handler internals.

**Comment by NelsonMinar** [comment]
Nice work! I agree your approach using Filters is a cleaner use of logger's infrastructure. You're simply creating a new Handler for each job that only logs messages for that thread. This approach has a bit more overhead (you now have N handlers each of which is seeing every log stream) but that shouldn't matter for only 10s of thread and a few log messages a second. I think either approach will work, go with what feels right to you!

**Comment by migurski** [comment]
I've been watching how this plays out in a full multi-source run, and I think my initial idea of where to put this code was wrong. It really needs to go inside `process_one.process()`, not outside. There needs to be a useful output log from a single-source run, and `jobs.py` needs to be doing less. I think I will go with the thread-based filter approach, but have it happen in `process_one`.

**Comment by NelsonMinar** [comment]
It'd be nice if the openaddr-process-one shell command still behaves the same. Maybe only install the filter + extra handlers when doing a multi-job run?

**Comment by migurski** [comment]
Agreed. I think I’ve successfully done that in 6b1f9e4, what do you think? The output.txt file, which was always created, now gets a full run of debug log output.

**Comment by NelsonMinar** [comment]
I think it's OK. Previously that `output.txt` file contained nothing useful (in my runs at least), now it contains the full debug log for the run.

Worth noting that this code won't work well if something logs millions of messages. (It buffers the whole log stream in StreamIO.) That's not a problem to me, but hopefully no one ever tries to log one message per row of data.

**Comment by migurski** [comment]
Should it instead be a file handler dumping to a temp file someplace?

**Comment by NelsonMinar** [comment]
Yeah, or even better dumping to the actual output file. But right now in practice it's no big deal. The biggest debug log from my jobs so far is us-va-fairfax at 400k.

Some people use logging to log a zillion fine-grained things but almost never actually switch on recording those log records. Personally I think that's a bad way to use logging.

**Comment by migurski** [comment]
To be on the safe side, I’ve converted it to a file handler in a60b733. I think this one’s done!
