### ISSUE TITLE
Add a page with history of each source over time

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#446]
It would be nice to see a log of each source, with every build displayed over time showing when failures happened, when sources changed, etc.

**Comment by iandees** [comment]
:+1:! At some point I want to parse the error log and categorize/summarize why a source is broken to help with the Most Wanted Sources list.

**Comment by iandees** [comment]
...and this would be a good page to surface this kind of thing.

**Comment by migurski** [comment]
What information would be useful? So far, I have thought of:

- Date
- Whether it succeeded
- Links to download cached and processed data files, if it worked
- Links to Github for the source at that point in time
- Links to a connected set or job, if applicable
- Number of addresses in the source

**Comment by migurski** [comment]
Would that be an excerpt of the log file, maybe?

**Comment by migurski** [comment]
What about coverage or location?

**Comment by iandees** [comment]
My theory on the "why it failed extractor" is a regex on the log file looking for common exceptions or error messages from the cacher or conformer. So not necessarily a log excerpt, but maybe a bit of text that is triggered by something in the log.

**Comment by iandees** [comment]
It might be interesting to know if a source has a `coverage` object over the course of its life. Ideally that wouldn't change very much, though, right?

**Comment by migurski** [comment]
It might not, but that's definitely interesting information.
