### ISSUE TITLE
Compressed GeoJSON Sources Fail Silently

### ISSUE THREAD

**Issue by iandees** [openaddresses/machine#447]
See for example:
- http://s3.amazonaws.com/data.openaddresses.io/runs/127096/logfile.txt
- http://s3.amazonaws.com/data.openaddresses.io/runs/123429/logfile.txt

Compressed GeoJSON is what I upload when I run esri2geojson locally.

**Comment by migurski** [comment]
I re-ran Bucks and Wyoming after being unable to recreate this error locally:

- https://github.com/openaddresses/openaddresses/pull/2106
- https://github.com/openaddresses/openaddresses/pull/2132

Bucks is fine but Wyoming died. I am having some suspicions about large GeoJSON sources parsed into memory and getting OOM-killed.

**Comment by migurski** [comment]
Both are good now, I think switching to a streaming GeoJSON parser did the trick.
