### ISSUE TITLE
HTTP and job timeouts

### ISSUE THREAD

**Issue by NelsonMinar** [openaddresses/machine#47]
Three of my jobs never completed last night: ca-bc-surrey us-tx-denton us-oh-hamilton. They're all ESRI-type sources and so require many HTTP requests. I'm assuming the server failed and somehow never closed the socket. (I'm surprised I never saw this happen before.)

**Comment by iandees** [comment]
Yea, we should definitely use the [first-byte timeout in `requests`](http://docs.python-requests.org/en/latest/user/quickstart/#timeouts). It could be something like 30 seconds probably?

**Comment by NelsonMinar** [comment]
Thanks Ian. My thought was [timeout=180](http://docs.python-requests.org/en/latest/user/quickstart/#timeouts) as a last-ditchabort, but I don't much care what the actual number is. FWIW the Requests timeouts are "not a time limit on the entire response download; rather, an exception is raised if the server has not issued a response for timeout seconds. (more precisely, if no bytes have been received on the underlying socket for timeout seconds)". So if bytes keep trickling in, the timeout won't fire.

I volunteer to add the code.

I also think the process-all Thread code should probably have a 30 minute time limit on any individual source, for the whole Thread. But that's a different sort of backstop with a different purpose.

**Comment by iandees** [comment]
It's rather hard to kill the connection mid-stream after a timeout since the execution path is deep inside `requests.get()` and won't return until we get all the data.

[This StackOverflow answer](http://stackoverflow.com/a/22096841) suggests using eventlet monkeypatching to run the `requests.get()` with what amounts to a supervisor thread.

**Comment by NelsonMinar** [comment]
I think the simple Requests timeout behavior is sufficient. It will give us a timeout if the server completely hangs. A perverse server could still hang the `get()` or `post()` if it trickles out a few bytes every once in awhile (which is what that StackOverflow answer is about) but that doesn't worry me too much.

I do think the larger job execution framework needs job-level timeouts, to protect itself from whatever perversity lies downstream. I'll have some data on those sources I mentioned above soon. us-tx-denton has been running an hour and is still downloading productively, but answers each request in about 30 seconds. One hour for 18M of JSON data :zzz:

**Comment by migurski** [comment]
For the Node version on `master`, [I kill off any process that outstays its welcome](https://github.com/openaddresses/machine/blob/3736b1dfb87d923ea9ce3b31befe65aae2c3e269/openaddr/__init__.py#L400). In `ditch-node`, jobs.py could be a place to put that responsibility.

**Comment by NelsonMinar** [comment]
OK, job timeouts will be great. The Requests timeout will also help. 3 of 137 ESRI sources failed in this way; I'm guessing it's a server bug we just have to protect ourselves from.

I ran the failed sources again and watched closely. All three ran slowly but consistently, one request answered every 10–30 seconds. Then all three hung at some point (no new data in 20+ minutes). gdb tells me the process is waiting in `__libc_recv()` and `netstat` shows the open TCP socket. Pretty sure the server is just hung, the Requests client timeout will help with that.

* ca-bc-surrey: ran 4 minutes, returned 5.5M of data
* us-oh-hamilton: 40 minutes, 48.6M
* us-tx-denton: 90 minutes, 27.8M

In every case the partial JSON data file is interrupted in the middle of a JSON object, it's not a complete line. Not sure if that's what the server gave us or it's an artifact of our own code buffering.

**Comment by iandees** [comment]
We might want to build in a backoff and graceful stop on the ESRI scraper so that we don't destroy a tiny municipality's ESRI server sitting on someone's 5 year old Dell desktop.

Maybe I could have it start at requesting a slice of 10 IDs, checking how long it took, and then request more until 100 or something and back off if a request ends up taking too long?

**Comment by NelsonMinar** [comment]
I committed the basic Requests timeout and hand-tested that normal downloads still work and that ca-bc-surrey did time out. (I've not been doing pull requests because it's a PITA; feel free to revert something I commit or change it as needed.)

@migurski, I'll leave this issue open as a placeholder for the job-level task killing unless you want to make a new issue for that.

@iandees, some sort of backoff sounds nice but I'd wait until someone complains before doing the work. I think we're quite polite, a single request at a time and only running every few hours. You know what would be great? To get advice from someone at ESRI. Maybe we could even get them to give us a bulk download! :angel:

**Comment by NelsonMinar** [comment]
For per-job timeouts, only 5 jobs took more than 30 minutes on my last run. The top 4 are all slow ESRI servers that did eventually get the job done. Denmark is a CSV source direct from a Danish site. The numbers are time in seconds.

````
9046.023  us-al-huntsville.json
8365.906  us-mi-ottawa.json
3782.447  us-va-city_of_chesapeake.json
2826.217  us-ca-marin_county.json
2000.911  dk.json
````

**Comment by NelsonMinar** [comment]
I took a quick look at how to do job timeouts. I didn't realize Python's `threading` module deliberately has no way to stop a thread. This [StackExchange answer](http://stackoverflow.com/questions/323972/is-there-any-way-to-kill-a-thread-in-python) has some hacky ways to do it; a call to `ctypes.pythonapi.PyThreadState_SetAsyncExc` or maybe `pthread_kill` to force the thread to exit. That's a little spooky but maybe OK for an emergency.

The other choice is to switch jobs to `multiprocessing`, processes have a `terminate()` method. I like this option better. I mentioned somewhere that multiprocessing interacts strangely with logging but it's [pretty benign](https://docs.python.org/2/library/multiprocessing.html#logging), the docs say that the worst that happens is two messages hit a Handler at the same time and they get intermixed in a logfile. I think even that's not a problem given Mike's strategy for per-job logging. But I'm a little confused about the multiprocessing environment, will require careful testing.

I note that I've run 600+ sources twice now and only ever encountered 3 that hung forever. And those 3 are now fixed by the HTTP timeout I committed. So while being able to stop a runaway job is a good idea, it may not be *essential* right now in order to do useful work.

**Comment by migurski** [comment]
I'm going to re-run the whole thing again today, see how it comes out. Since the current sources are passing, I'm going to move this out of the Ditch-Node milestone as well.

I’ve done a small amount of testing with `signal` as well, and I think it will help generate meaningful logs even for killed processes:

https://gist.github.com/migurski/433568eb2944389b3b5f

**Comment by NelsonMinar** [comment]
I'm doing a full run with `openaddr-process` now too. Doing this has convinced me we want to use `multiprocessing` for job management, not `threading`. If we switch to that interrupting runaway jobs gets easy. No more getting mired in some ancient ESRI server.

Your signal code is promising; I note it uses multiprocessing. Good thing, apparently [Python does not support](https://docs.python.org/2/library/signal.html#module-signal) delivering signals to child threads. (Linux sort of does, but POSIX signals+threads are notorious.)

Signals are the right way with multiprocessing. `Process.terminate()` just sends a `SIGTERM` to the subprocess, just like killing from the command line. I think that will be sufficient for aborting a broken job, no need to install custom signal handlers or anything.

**Comment by migurski** [comment]
Seems clear that we must switch to `multiprocessing`. I [tried placing the signal handler setup in the parent process](https://gist.github.com/migurski/433568eb2944389b3b5f), and it worked just as well while still correctly trapping and logging the result. This looks to be a winner.

**Comment by NelsonMinar** [comment]
I've worked on a couple of multiprocessing approaches. The simple way is to replace `Thread` with `multiprocessing.Process` and reuse the rest of `jobs.py` task queueing infrastructure. The quick hack sort of works, but I think we now have to work on sharing the queue structure between processes.

I'm now pursuing a second approach using `multiprocessing.Pool` to do the queuing. That will replace about 80% of `jobs.py`. I have [some sample code](https://gist.github.com/NelsonMinar/e11eeb524b4940a40ddf#file-mp-py) that includes using SIGALRM to set a total per-job timeout to interrupt runaways. It seems to work, tomorrow I'll see if I can shoehorn this approach into our code.

**Comment by migurski** [comment]
In lieu of doing this right I’ve added a cooperative timeout in f7976f0.

**Comment by NelsonMinar** [comment]
I've got a WIP in the branch pool that seems to be working with multiprocessing. The important code is all in `jobs.py`. Here's the diff, but it's almost entirely a new file. https://github.com/openaddresses/machine/compare/ditch-node...pool

I've tested this with a 5 second timeout and 5 sources (4 S3 data files, 1 ESRI source). So far it looks good, you even get the stack trace of where the job was when it was killed!

I don't know how to test this thoroughly. Things to watch out for:
1. @migurski does this write all the bits of post-job-state you expect? It looks right but I don't understand all the code.
2. How robust is this? Only way to be sure is run it a lot.
3. Does killing a process cause any problems? Any open files / memory / resources left consumed?
4. Are signals being delivered correctly all the time?
5. Does Ctrl-C from the keyboard work sensibly? How about killing from the command line?
6. Are the logfiles correct?

I'm fairly confident in all the above but the second one, robustness.

**Comment by migurski** [comment]
The only one I’m not confident about if the post-job-state. If `JobTimeoutException` gets triggered someplace inside the process due to an alarm, I don’t think `jobs.py` should do anything special to handle it. Looking deeper, I’m not sure it will ever see the exception, because it will get caught in `process_one` and logged so `except JobTimeoutException as timeout_ex` should never be reached.

**Comment by NelsonMinar** [comment]
I've added a feature where you can kill -USR1 the main process and it will terminate all jobs and quit processing sources. It will still then try to collect the results, report on them, upload them S3, etc. It's one last ditch way to rescue a run that is stuck somehow.

I'm feeling pretty good about this code. I'm just going to keep running it repeatedly today to see how it performs in different circumstances. I'd say about 15 runs have worked fine despite various forms of timeouts, SIGUSR1s, etc. However one test run I failed in a troubling way; it completed 43/44 jobs with no problem, but one job us-va-city_of_norton.json never got started. It was in the task queue, the pool had not indicated all jobs completed, but it never started that one up. That could be some bug in `multiprocessing.Pool` or could be a scary indicator that some way we're timing jobs out is breaking multiprocessing. (I even tried killing all the child pool processes; they respawned, but the work was not assigned).

(To Mike's comment, I added a comment in the code about how JobTimeoutException should normally be handled by `process_one`. Still catching it just in case...)

**Comment by NelsonMinar** [comment]
I just noticed Travis is failing to run one test, see https://travis-ci.org/openaddresses/machine/builds/47440301 for example. It's working on my home machine though. The failure seems related to fake S3 stuff, @migurski any idea? Any change Travis has problems with multiprocess code?

**Comment by migurski** [comment]
I looked at the failing test; it’s absolutely a result of `FakeS3` not being wise to multiple processes. I’ll fix.

**Comment by NelsonMinar** [comment]
Any thoughts on using [setproctitle](https://pypi.python.org/pypi/setproctitle/) to set the process title for a task? I think it'd be really neat for the source filename to show up in "ps". It's a small external dependency or else I would have already added it.

**Comment by NelsonMinar** [comment]
Here's a sample run of 44 jobs with 5 minute timeouts. That took about 9 minutes. 36 ran fine, 3 timed out, a few others hand download or conform errors.

http://com.somebits.secondmedium.s3-website-us-east-1.amazonaws.com/runs/1421619251.336/index.html

**Comment by migurski** [comment]
Wait, no, it was failing because `upload_states()` had been commented out. Fixed in 0e930c0.

**Comment by migurski** [comment]
I like the idea of setting the process title for visibility from `htop`.

**Comment by NelsonMinar** [comment]
It looks nice in `htop`! Note there's an option to `htop` for "update process names" that you'll want to turn on.

I haven't tested this carefully, but I believe if you kill one of the job subprocesses it just aborts that one and the pool will merilly fork off a new process and keep working.

The way timeouts abort jobs mean that temporary files aren't being cleaned up, at least in my conform code. There's some /tmp/openaddr-extracted litter now, from when jobs are aborted after the download but before the conform finishes.

**Comment by NelsonMinar** [comment]
I did a run of all 578 sources with conforms, with a 60 second timeout. It more or less worked, 17M rows in about 40 minutes.

The same bug I mentioned above showed up again, one job not finishing. The pool acted like it had no work to assign but it had not exited and I was at 577/578 completion. Earlier I'd noticed one of the worker processes was stalled (you can see this in `htop`; the name of the process never changes to a job source name). I gave that idle worker a SIGTERM and the pool spawned off a new job, but I bet whatever job had been assigned to it got lost forever. This might be a bug in `multiprocessing.Pool` or it might be a bug related to how we're killing jobs. It's rare and I don't know how to reproduce it. The way to understand it would be to get inside a broken process and start looking at the state of the pool.

As before, we can recover a stalled full run by using SIGUSR1 to kill all processing when it looks like it's done. It's ugly, but at least we don't lose all the work.

I talked it over with Mike and I'm going to go ahead and merge the new multiprocessing code to `ditch-node`. It's better than the threading code now.

**Comment by NelsonMinar** [comment]
I've now merged the `pool` branch in to `ditch-node`, the multiprocessing port is done. Yay!
