### ISSUE TITLE
Switch from user AWS credentials to IAM Role approach

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#472]
We’re passing around and storing AWS keys and secrets in a bunch of places, and we should switch to an anonymous IAM role-based approach to make for more granular control.

Things we know now:
- EC2 instances launched in a given role offer temporary AWS credentials that can be used to talk to S3, etc.
- Boto likes to detect and use these credentials, so we can stop storing them in configuration files if we want
- AWS policies for S3 are basically known

Things we do not know:
- How or whether to write AWS policies for EC2 that allow for launch and termination of temporary instances, but prevent deletion of permanent instances
- How our unit tests will behave when AWS credentials switch to contextual / environmental variables

Things to do:
1) [x] Configure current instances and autoscale groups to use a new role
2) [x] Configure Cloudwatch namespace instead of hard-coding it
3) [x] Start to use `configs` and `logs` directories in the main data bucket for running new instances under `openaddr-run-ec2-command`
4) [x] Transition away from explicit AWS credentials in config entirely

**Comment by migurski** [comment]
So far, these have been the best summaries of EC2 IAM interactions: 

- https://aws.amazon.com/blogs/security/demystifying-ec2-resource-level-permissions/
- http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ExamplePolicies_EC2.html

**Comment by migurski** [comment]
Status report: I’m making decent progress on this issue over a series of PRs, though it's dragging along a bunch of related issues. The shape I’m aiming towards is an EC2 setup where IAM roles make it possible for us to operate machines from "outside", which means that we stop storing configuration parameters on AMI’s and instances entirely, and instead pull them from S3 when a new instance is started. The IAM Role lets us do that by granting S3 access to private, read-only configuration data at boot time.

We should also stop logging into them with SSH. Instead, I’d like to switch to a blue/green deployment setup where releasing a new version of machine code consists of booting a fresh instance, waiting for a health check to clear, and then rolling over the existing instance in an ELB.

**Comment by iandees** [comment]
👏 👏  I like this!

One of my many todo-tabs has Skyliner in it with the intention of setting it up with the OpenAddresses account so we can try using their workflow for deploys.

**Comment by migurski** [comment]
Yeah could be really interesting. I’m explicitly modeling this on some of their choices, without tripping the Docker deployment part. Another thing I don’t know yet: where to put logs for persistent processes like [the Flask app](https://github.com/openaddresses/machine/blob/master/docs/components.md#webhook) or [the dequeuer](https://github.com/openaddresses/machine/blob/master/docs/components.md#dequeuer). Some possibilities:

- Use CloudWatch: http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cwl-metricscollected.html
- Rotate them to S3: http://www.dowdandassociates.com/blog/content/howto-rotate-logs-to-s3/

**Comment by iandees** [comment]
I use [PaperTrail](https://papertrailapp.com/) with all of my Heroku-ey stuff and it works very well. Rotating to S3 makes lots of sense, though.

**Comment by migurski** [comment]
Update: success! Webhooks and Workers are now configured as auto-scaling groups in AWS. The launch process for releasing a new version of the code is described here: https://gist.github.com/migurski/51f2b3c62348c93d8e62f7742c8668d4
