### ISSUE TITLE
Fix cache type guessing

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#48]
We have two related problems connected to bad guesses about content-type for cached files. We’re not using the [`compression` core tag](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#core-tags) as a hint, and in many cases [sources mis-report types](https://gist.github.com/migurski/8fe9d98e760795eaa1a7). We’re also not using HTTP status codes to skip processing of 4xx and 5xx responses.

* [ ] Use `compression` tag to recognize zip files.
* [ ] Use HTTP status responses to recognize missing/bad data.
* [x] Recover from exceptions inside `process_one.process()`.

See sample error log below.

```
  DEBUG: Content-Type says "text/html" for http://stjamesassessor.com/Downloads/DownloadFile.asp?FileID=4206
  DEBUG: Guessed us-la-st_james-72eb71dd.html for http://stjamesassessor.com/Downloads/DownloadFile.asp?FileID=4206
   INFO: Requesting http://stjamesassessor.com/Downloads/DownloadFile.asp?FileID=4206
: Downloaded 158 bytes for file out/process_one-_el6uX/cache-AWFAnY/http/us-la-st_james-72eb71dd.html
   INFO: Cached data in file:///home/ubuntu/out/process_one-_el6uX/cached/us-la-st_james-72eb71dd.html
  DEBUG: URL says ".html" for file:///home/ubuntu/out/process_one-_el6uX/cached/us-la-st_james-72eb71dd.html
  DEBUG: Guessed us-la-st_james-1f0ec642.html for file:///home/ubuntu/out/process_one-_el6uX/cached/us-la-st_james-72eb71dd.html
  DEBUG: File exists out/process_one-_el6uX/conform-zetfy_/http/us-la-st_james-1f0ec642.html
   INFO: Downloaded to ['out/process_one-_el6uX/conform-zetfy_/http/us-la-st_james-1f0ec642.html']
  ERROR: Error while running process_one.process

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openaddr/jobs.py", line 61, in _run_process_one
    result = process_one.process(path, destination, extras)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/process_one.py", line 38, in process
    conform_result = conform(temp_src, temp_dir, cache_result.todict())
  File "/usr/local/lib/python2.7/dist-packages/openaddr/__init__.py", line 149, in conform
    decompressed_paths = task2.decompress(downloaded_path, workdir)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/conform.py", line 108, in decompress
    with ZipFile(source_path, 'r') as z:
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
```

**Comment by NelsonMinar** [comment]
14 files in my last run threw a BadZipfile exception.
ca-ab-strathcona-county ca-bc-langley ca-bc-west_kelowna ca-ns-halifax us-ca-san_diego us-fl-collier us-ga-glynn us-la-st_james us-ma us-nc-charlotte us-nc-columbus us-ri us-tx-round_rock us-va-city_of_falls_church

**Comment by migurski** [comment]
Started usefully logging those exceptions in 252145d.

**Comment by migurski** [comment]
Filename extensions are still often mis-guessed from common mimetypes like `application/xml` or `text/plain`.

**Comment by migurski** [comment]
Most of the remaining `BadZipFile` examples I can find are actual bad zip files, and should throw errors. Closing this issue because I am no longer seeing cases with a known fix.
