### ISSUE TITLE
Build generic geoid status JSON

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/machine#480]
I'd like to recreate the choropleth maps on http://results.openaddresses.io showing results per county, state, and country (and sometimes city) using Tangram so I can add interactivity. Think hover over county that is grey and it’ll show you the name, click on it and infowindow comes up with basic search term links that might result in data, link to create new Github issue with some of the title and body filled in.

@migurski pointed me as the shapefiles:

- https://github.com/openaddresses/machine/tree/master/openaddr/geodata

But there doesn't seem to be a simple, convienent table of results (e.g. CSV or JSON) that is built each run that could drive this map. This issue covers adding that result and publishing it publicly.

**Background:**

@migurski did point at this code:

- https://github.com/openaddresses/machine/blob/master/openaddr/render.py#L270
- https://github.com/openaddresses/machine/blob/master/openaddr/render.py#L75
- https://github.com/openaddresses/machine/blob/master/openaddr/ci/__init__.py#L649-L651

And said this link is "best":

- https://results.openaddresses.io/state.txt 

With `sources_dir` at:

- https://github.com/openaddresses/openaddresses/tree/master/sources

**Comment by migurski** [comment]
The missing piece here may be to include coverage information (FIPS, ISO, and geometries) someplace in sources. Are you imagining that this map would be something you'd generate periodically, or something you'd want to reload live regularly?

**Comment by nvkelso** [comment]
Ideally it’d be as fresh as any other OpenAddresses map (it would be
equivalent to the existing choropleth maps).

I’d like a single file to load – so the summary result of looping over
individual sources.

**Comment by migurski** [comment]
The current choropleths get regenerated every couple days. I could add GeoJSON output alongside the current PNG output to support this use.

**Comment by iandees** [comment]
I was going to point out that a simple mapping between ISO/geoid code and coverage status wouldn't work because some sources don't match to single ISO/geoid (like Texas "statewide" for example). A GeoJSON would be a great compromise, though.

**Comment by nvkelso** [comment]
I dig GeoJSON output, groovy!

**Comment by nvkelso** [comment]
@iandees also reminded me of https://docs.google.com/spreadsheets/d/1HFm0YbFDC5YKkHKFt89EKdhpyaCCIo_CiDFjBNq4PoI/edit#gid=0

**Comment by migurski** [comment]
What properties should each GeoJSON feature have? I can think of source path, date last cached, and date last processed. What else?

**Comment by nvkelso** [comment]
I’m also interested in the stuff in “coverage”, like:

* name
* status (the dark green, light green, and oranges)
* country
* state
* ISO 3166 (alpha2)

In additon to your:

* source path (which I think is enough of a pointer to things like: type,
data, website, and license)
* date last cached
* date last processed

Is it also possible to mark how many addresses were in this source?

**Comment by migurski** [comment]
Status is a tricky one, since basically all of them have been green at some point. The last-processed date will tell you whether something appears to have fallen off, unless you'd like a per-batch version of this? It’s the difference between these two maps:

- General availability, with mostly everything in gree: https://s3.amazonaws.com/data.openaddresses.io/render-usa.png
- Last week's batch set with some failures: https://s3.amazonaws.com/data.openaddresses.io/sets/133364/render-usa.png

**Comment by nvkelso** [comment]
Preferably both, like:

   - https://s3.amazonaws.com/data.openaddresses.io/render-usa.geojson
   - Last week's batch set with some failures: https://s3.amazonaws.com/data
   .openaddresses.io/sets/133364/render-usa.geojson

**Comment by migurski** [comment]
Would [something approximately this shape](https://github.com/openaddresses/machine/files/670297/out.geojson.zip) work?

**Comment by nvkelso** [comment]
Link 404s for me :(

**Comment by migurski** [comment]
Try the link on Github? I replaced it after the file upload 404'd. Or try http://data.openaddresses.io/render-world.geojson because it's real now. 

-mike.

---------------------------------------
michal migurski http://mike.teczno.com

**Comment by nvkelso** [comment]
Neat! I got this one to load in QGIS :)

But something is weird with the file. When viewing that URL in Safari it shows a ? box, and saving it prompts me to save it as a PNG. If I change the extension to .geojson it will open in QGIS fine.

Could the source be the path & filename listed here and/or/instead? It would be nice to link to the src to edit it if the status is not "good".

- https://github.com/openaddresses/openaddresses/tree/master/sources

Also, is it possible to generate an alternate file that would be bigger file size but include all the features without a source? That way someone could mouse over the missing feature to research sources.

<img width="1146" alt="screen shot 2016-12-23 at 22 11 56" src="https://cloud.githubusercontent.com/assets/853051/21465552/1701d26a-c95d-11e6-9328-c14228d9b48b.png">

**Comment by migurski** [comment]
The PNG thing is because I accidentally set all the uploads to have `image/png` mime-types, so I will fix that. I’ll also update the filenames to be real.

A bigger file would be much, much bigger, with all the world's admin 1 areas along with U.S. geometries. Are you thinking we would use a tiled version of this so it's not a mega-download?

**Comment by nvkelso** [comment]
Yes on tiled, could it be auto uploaded to Mapbox like the dot map?

**Comment by migurski** [comment]
Probably, might take some additional help from someone though. @sbma44 created the upload script for the dotmap, and I am pretty unfamiliar with the Mapbox account or how uploads there should work.

**Comment by migurski** [comment]
There's a new version of the file at the URL above, with the changes mentioned in #503.

**Comment by migurski** [comment]
Last things to do for this issue:

- Names of areas and dates of most recent cache/process in a new column
- Links to GeoJSON files from https://results.openaddresses.io/index.json
- GeoJSON renders for each batch set

Future things for another issue:

- Bigger alternate file with all world administrative areas
- Tiled output

**Comment by migurski** [comment]
The new rendered GeoJSON can be found linked from https://results.openaddresses.io/index.json, with individual set renders behind `latest_set_url`, e.g. https://results.openaddresses.io/sets/137680.json, https://results.openaddresses.io/sets/139525.json etc.
