### ISSUE TITLE
Esri cacher doesn't handle 'join' function correctly

### ISSUE THREAD

**Issue by iandees** [openaddresses/machine#481]
The Esri cacher [tries to figure out which fields to request](https://github.com/openaddresses/machine/blob/master/openaddr/cache.py#L330) by inspecting the `conform` object of the source. When it encounters a `dict`, it [looks for the `field` attribute](https://github.com/openaddresses/machine/blob/master/openaddr/cache.py#L321) and adds that to the list of columns to request. In the case of the `join` function, which specifies the name should be `fields`, we end up with a `None` in the list of fields and this function fails.

The fix is to add `field` or `fields`.

Related to this error: https://s3.amazonaws.com/data.openaddresses.io/runs/133223/output.txt

**Comment by migurski** [comment]
What’s a source definition that exhibits this behavior?

**Comment by iandees** [comment]
Any source that uses the `join` function. e.g. this one: https://github.com/openaddresses/openaddresses/blob/232785bf2a57dc32bac0b8530a826d04b5c45ce1/sources/pl/zachodniopomorskie.json#L22-L26
