### ISSUE TITLE
Use org membership instead of listing to determine upload status

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#482]
Use https://developer.github.com/v3/orgs/members/#check-membership in `ci.webauth.user_information()`. Currently private members are invisible.

**Comment by iandees** [comment]
I do this [here](https://github.com/osmus/membership/blob/master/main.py#L129) and it doesn't seem to work quite right. Let me know if you figure it out.

**Comment by migurski** [comment]
It did seem to work when I tested it against some of my own private group memberships. I’ll let you know.
