### ISSUE TITLE
Allow `srs` override for non-CSV sources

### ISSUE THREAD

**Issue by trescube** [openaddresses/machine#500]
According to @iandees in https://github.com/openaddresses/openaddresses/pull/2275#issuecomment-268293110

an invalid .prj can be packaged with a shapefile source.  A fix for this issue would allow a source to specify an `srs` field that would override what's specified in the .prj file.

**Comment by migurski** [comment]
I am surprised we didn't allow this already!

**Comment by trescube** [comment]
This would also allow us/nj/statewide to work since the GDB data source doesn't seem to contain a projection:  

https://s3.amazonaws.com/data.openaddresses.io/runs/135600/output.txt

**Comment by migurski** [comment]
I've looked deeper into the New Jersey data, and it looks like what's actually happening is that it’s got multiple layers. The address layer does have a projection, but our code does not understand how to specify or select a layer. So that will need to be done separately.
