### ISSUE TITLE
Upgrade to GDAL 2.x

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#512]
It might not be possible to get non-UTF8 strings out of OGR sources with GDAL 1.11.x, based on posts from @NelsonMinar, @rouault, and an old issue on this repo:

- https://nelsonslog.wordpress.com/2015/01/15/ogrpython-vs-unicode/
- https://lists.osgeo.org/pipermail/gdal-dev/2016-January/043575.html
- https://github.com/openaddresses/machine/issues/42

This is currently affecting several Italian sources. We'll need `Feature.GetFieldAsBinary` to be present.

**Comment by NelsonMinar** [comment]
I'm guessing be-flanders no longer works for the same reason as your Italian sources. Rereading issue #42 I remember now that our workaround for GDAL 1.11.x would only work in Python 2. The test case I was using then was be-flanders; according to [the machine logs](http://results.openaddresses.io/sources/be/flanders) that stopped working between Oct 22 and Oct 29. Was that when you swapped production to Python 3?

My impression is the GDAL 1.11.x bindings simply don't work for Python 3 for all our input files. I agree upgrading GDAL may be the best course of action.

**Comment by migurski** [comment]
Yes, October does sound like when I switched to Python 3, and [I can see on the dashboard](https://results.openaddresses.io/dashboard) that there's an overall slight dip in address count then.

**Comment by migurski** [comment]
The tests passed cleanly when upgrading, and now we’ll get the benefit of `getFieldAsBinary()`. I'm going to hold off on merging #514 until I have a bit time set aside; it may be a breaking change to do this on an existing AMI with GDAL 1.11 already installed and a slightly different set of apt-sources.

**Comment by NelsonMinar** [comment]
Are the Italian source and `be-flanders` working now? IIRC GDAL is pretty confusing about how it handles this stuff, it may take a bit more doing.

**Comment by migurski** [comment]
They _should_ work with this, but I'm just nearing the end of the major version upgrade process in AWS and I'll call for them to be re-run when it’s complete.
