### ISSUE TITLE
Add South America extract to results.openaddress.io

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/machine#519]
With the new Brazil data adding millions++ of addresses it'd be nice to download that without resorting to the `global` option.

http://results.openaddresses.io

**Comment by migurski** [comment]
What’s a good list of SA countries we can use and link to, similar to the other collections?

**Comment by migurski** [comment]
…Also, with Mexico, should the extract cover everything south of the U.S./Mexico border?

**Comment by nvkelso** [comment]
I think it should be South America alone, unless you went with a generic "Americas (excluding USA)" download. (Mexico is in North America.)

Using the Who's On First Spelunker for countries in South America yields results I generally agree with:

* `85632505` Argentina
* `85632623` Bolivia
* `85633009` Brazil
* `85633057` Chile
* `85632519` Colombia
* `85632261` Ecuador
* `85632397` Guyana
* `85632355` Paraguay
* `85632521` Peru
* `85632443` Suriname
* `85632511` Uruguay
* `85632317` Venezuela

Viewed as 2-char ISO codes: 

* `ar`
* `bo`
* `br`
* `cl`
* `co`
* `ec`
* `gy`
* `pe`
* `py`
* `sr`
* `uy`
* `ve`

Then there is the old ball: `85632233` French Guiana with ISO code `gf`, which is kind of like Alaska in that it's an overseas region of France. But it has a different ISO code than metropolitan France so it's okay to include in this list.

**Comment by migurski** [comment]
<img width="988" alt="soon" src="https://cloud.githubusercontent.com/assets/58730/22045366/9b2af7f4-dcce-11e6-8ac4-88c543f11a18.png">

**Comment by iandees** [comment]
😭 COMIC SANS 😭

**Comment by migurski** [comment]
The typeface of champions.

**Comment by migurski** [comment]
<img width="993" alt="screen shot 2017-01-19 at 2 44 46 pm" src="https://cloud.githubusercontent.com/assets/58730/22128521/ddbe787e-de55-11e6-92f3-06bcb452289b.png">
