### ISSUE TITLE
job queue not completely insulated from worker crashes

### ISSUE THREAD

**Issue by NelsonMinar** [openaddresses/machine#52]
Over in issue #51 migurski reported

Getting better. I just had a whole run crash on this:

```
MainThread 589851.6 DEBUG: Requesting http://gisdata.cityofchesapeake.net/public/rest/services/A_POL_Basemap/MapServer/8/query
MainThread 589898.8 INFO: Converted to out/process_one-jt9HBi/conform-hUZ9tU/converted/us-sc-lexington-59dc607d.csv
MainThread 589908.5 INFO: Processed data in /home/ubuntu/out/process_one-jt9HBi/out.csv
MainThread 589908.8 INFO: Starting task for /var/opt/openaddresses/sources/us-ms-hinds.json with PID 15414
MainThread 589909.5 DEBUG: Downloading /arcgis/rest/services/Viewers/Hinds/MapServer/3 to us-ms-hinds-98c08b37.json
Traceback (most recent call last):
File "/usr/local/bin/openaddr-process", line 9, in 
load_entry_point('OpenAddresses-Machine==1.1.1', 'console_scripts', 'openaddr-process')()
File "/usr/local/lib/python2.7/dist-packages/openaddr/process_all.py", line 47, in main
process(s3, paths.sources, run_name)
File "/usr/local/lib/python2.7/dist-packages/openaddr/process_all.py", line 113, in process
results = jobs.run_all_process_ones(source_files, 'out', source_extras)
File "/usr/local/lib/python2.7/dist-packages/openaddr/jobs.py", line 114, in run_all_process_ones
completed_path, result = result_iter.next(timeout=report_interval)
File "/usr/lib/python2.7/multiprocessing/pool.py", line 659, in next
raise value
IOError: [Errno 2] No such file or directory: '/20150119/us-sc-lexington.json'
MainThread 589975.4 DEBUG: Requesting http://gis.mesaaz.gov/mesaaz/rest/services/Address/AddressIndexAcella/MapServer/0/query


`out/us-sc-lexington` is empty.

**Comment by NelsonMinar** [comment]
Huh, was `/20150119/us-sc-lexington.json` actually missing? Weird path, but maybe it couldn't load a source file it expected?

Looking at [the code](https://github.com/openaddresses/machine/blob/6370898b2ff060b5467aaf99175c5ef648820607/openaddr/jobs.py#L111), it looks like if a worker manages to throw an exception it comes out of next(), and nothing handles it in the master job process. Ordinarily this doesn't happen because `process_one.process` catches all exceptions, but maybe this one leaked through. I think adding a blanket `catch Exception` [right around here](https://github.com/openaddresses/machine/blob/6370898b2ff060b5467aaf99175c5ef648820607/openaddr/jobs.py#L111) could make the job queue robust to this kind of task failure. Will need to make sure `StopIteration` still propagates, though. I'll work on this in code in a couple of hours if I don't hear otherwise.

**Comment by migurski** [comment]
I'll dig; I’m trying Lexington alone to see what’s up.

**Comment by migurski** [comment]
Hm, Lexington works fine alone. My current guess is that there's something different about running `process-all` with existing information from a previous run, I'll dig more.

**Comment by NelsonMinar** [comment]
Oh yeah, I ran into that bug too, with the /20150119/ in the path. I just been avoiding it by starting with empty S3 bucks, because I've not been worrying about that part of the code. Anyway I'll still be sure that any Task exception won't break the whole queue, just the one Task.

**Comment by NelsonMinar** [comment]
@migurksi, I'm closing this bug because I fixed the job queue problem. I think there's still a bug in the run management code when using information from a previous run, the underlying cause of the exception you reported. I won't harass you by opening yet another issue for that :-)

**Comment by migurski** [comment]
I opened #53 for this.
