### ISSUE TITLE
Extend ESRI server timeout

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#528]
…for slow sources, as suggested in https://github.com/openaddresses/openaddresses/pull/2396#issuecomment-274246767.

@iandees, it looks like `EsriDumper` would take a `timeout` option [on line 354 of `cache.py`](https://github.com/openaddresses/machine/blob/4077ded8f51897680bb700f5ca85461c14ba95b4/openaddr/cache.py#L354) according to [the constructor in `dumper.py`](https://github.com/openaddresses/pyesridump/blob/master/esridump/dumper.py#L10-L13), is that right?

**Comment by iandees** [comment]
Yep! That's looks right.
