### ISSUE TITLE
Confusing error when .zip detected, but compression:true not set

### ISSUE THREAD

**Issue by iandees** [openaddresses/machine#533]
In https://github.com/openaddresses/openaddresses/pull/2402, the `data` is an HTTP download of a .zip file, but the source doesn't specify a `"compression": "zip"`. The [machine log](https://s3.amazonaws.com/data.openaddresses.io/runs/150325/output.txt) says "Decompressed to 1 files", even though it didn't decompress anything and fails.

**Comment by migurski** [comment]
Weird, I’ll look into it.
