### ISSUE TITLE
bad ESRI sources yield 0 row CSV files that don't look like errors

### ISSUE THREAD

**Issue by NelsonMinar** [openaddresses/machine#55]
In a [run I did last night](http://com.somebits.oafull.s3-website-us-east-1.amazonaws.com/runs/1421723433.179/index.html) 27 of 578 sources resulted in a 23 byte out.csv file, something that just contains the headers. All of these sources have the same problem: "Downloaded 0 ESRI features" and a cache.json file that is an empty FeatureCollection.

One problem is that these ESRI sources aren't being processed correctly. It'd be nice to look at why. It could be the service is just broken in which case it'd be nice to signal that as a download error somehow.

The other problem is that the result collector should probably flag this kind of an output as an error. Maybe some fail safe in the reporting code that if the CSV file is too small it's assumed to be an error?

This is just a nice-to-have; it's pretty obvious to the user something went wrong. Here's the source list:

us-ia-polk us-pa-beaver us-ia-linn us-mn-polk us-mn-yellow_medicine us-mn-wadena us-va-roanoke us-tx-hurst us-in-madison us-mo-barry us-ga-gordon us-ct-avon us-nv-nye us-nv-lander us-nv-henderson us-tx-north_richland_hills us-mo-st_louis_county us-tx-colleyville us-tx-dallas us-va-fluvanna us-il-tazewell us-ar us-ct-lyme us-tx-keller us-mi-muskegon us-tn-memphis us-fl-alachua

**Comment by iandees** [comment]
The few sources that I spot checked in your list are 500'ing on the server side. If we do a check to make sure the first request to the ESRI server is a 200 and error on anything else we can probably surface this as the right kind of error.

**Comment by NelsonMinar** [comment]
I think this bug is fixed in the 3c1155d code that's currently in the branch esri-outputs-csv
