### ISSUE TITLE
Serve compressed CSV

### ISSUE THREAD

**Issue by NelsonMinar** [openaddresses/machine#56]
Product proposal: we should serve people compressed output files. Unfortunately S3 won't do this for us, in particular it won't do gzip compression in HTTP. There's a bunch of workarounds, I think the best choice for us is to stop serving `out.csv` files and instead serve `out.csv.gz` or maybe `out.zip`. The drawback is it puts the burden on the client to have to manually uncompress the files they download.

dk's out.csv is 130MB. gzipped that's 26MB. (bzip2 is 24MB) us-ca-los_angeles_county goes from 126MB to 33MB. So we're talking about a ~75% space, bandwidth, and time savings.

We could extend this idea to other large products, particularly any `cache.json` or `cache.csv` files.

**Comment by iandees** [comment]
If we gzip the CSV before we put it on S3 and then tell S3 that it's
gzipped they will serve it with the appropriate headers that trigger a
browser to decompress it before showing/downloading it to the user.

**Comment by NelsonMinar** [comment]
Unfortunately always serving gzip breaks HTTP; you're not supposed to send it gzip unless the client asks. It only works if the browser expects and supports `Content-Encoding: gzip`. `curl` and `wget` both explicitly don't deal with gzip by default.

I set up a demo of this at http://com.somebits.s3gzip.s3-website-us-west-2.amazonaws.com/gzipped.txt. It loads fine in Chrome. It fails with `curl` but works with `curl --compressed`. `wget` doesn't even have a way to decompress, you have to do `wget | gunzip`. That's why I think it's better to explicitly name the file `.csv.gz`; the user will know what to do with it.

Lots more detail about this weirdness in S3 [on my blog](https://nelsonslog.wordpress.com/2015/01/21/s3-vs-gzip-encoding/).

**Comment by NelsonMinar** [comment]
@migurski mentioned running out of disk in some of his EC2 runs. If we only produce compressed products then we can save a lot of disk while a job is running. A full run of 790 sources wrote 28G to disk. If I tar + gzip the whole directory that gets to 17G, 60%. Not an enormous savings but it can only help. (I suspect it's not more because a lot of the 28G is cached shapefile zips that are already compressed.)

**Comment by NelsonMinar** [comment]
We had a discussion in Slack and @migurski, @iandees, and I all agree we should zip the CSV output and serve `.zip` files instead of `.csv` files. This lets us avoid the whole S3/gzip encoding question. Also allows us to put extra files into the product if we want, maybe a `.vrt` file or some other metadata.

**Comment by migurski** [comment]
PR #84 does the thing—one of you want to have a look before I merge?
