### ISSUE TITLE
Successful source but with errors in log

### ISSUE THREAD

**Issue by trescube** [openaddresses/machine#560]
While adding [Grand Traverse County, MI](https://github.com/openaddresses/openaddresses/pull/2549), the machine reports build success, but the error log is reporting [an error](https://s3.amazonaws.com/data.openaddresses.io/runs/159147/output.txt) and the data file is empty.  It looks like an error occurs while calculating some geometry.

**Comment by migurski** [comment]
That’s at the preview step; it's failing to generate a preview because it's not finding any points in the sources. I’m thinking it should probably throw an error here, that specifically calls the source out as empty.
