### ISSUE TITLE
Fix geometry type detection for ESRI sources

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#57]
They used to be converted to GeoJSON, but as in #34 we decided to change them to CSV. We’ll need for excerpt to understand where geometry type comes from.

**Comment by NelsonMinar** [comment]
Once this is added back please undo my removal of the tests in 171fd8b8df0842879f726159ea310144d094e9b1 and bae0efed29ad1439e87c3f2d09ff692d77361c32
