### ISSUE TITLE
State total number of sources (not just successful sources)

### ISSUE THREAD

**Issue by nvkelso** [openaddresses/machine#571]
The top level paragraph on http://results.openaddresses.io lists out:

`This is a summary view of OpenAddresses data. 406,899,591 addresses have been processed as of Saturday, Mar 04, 2017. Out of all sources, 1,895 have completed.`

Instead of saying `Out of all sources` I recall we used to say how many total sources there were as a number. I miss that number and want to see it again. Either here or somewhere else, like the [Dashboard](http://results.openaddresses.io/dashboard) which could use a sentence next to each of those charts saying what the current value is.

**Comment by migurski** [comment]
Something a bit more like [the individual set pages](https://results.openaddresses.io/latest/set), then?

> This is a summary view of OpenAddresses data. 375,300,950 addresses were processed Saturday, Mar 04, 2017. Out of 1,965 total sources, 1,553 were completed. 365 sources failed cache, 47 cached but not processed.

**Comment by nvkelso** [comment]
Yes, that! 35 sources away from 2k! :)
