### ISSUE TITLE
Fix whatever is making the job pages miss data

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#574]
Sometime between these two jobs, the various log and preview links disappeared from the job pages:

- Before: https://results.openaddresses.io/jobs/96e1fba5-8704-4a37-ac28-9ca21e228249
- After: https://results.openaddresses.io/jobs/2134dfb5-5770-4b75-8e70-f8022494262b

What happened around lunchtime PST on March 7?

**Comment by iandees** [comment]
You switched to using the runstate object instead of dicts. Maybe they're not getting populated somewhere?

**Comment by migurski** [comment]
It is definitely a safe assumption that I am to blame. 😳
