### ISSUE TITLE
Coverage issue with Santa Catarina state, Brazil

### ISSUE THREAD

**Issue by astoff** [openaddresses/machine#588]
Somehow, the state of Santa Catarina, Brazil (source json [here](https://github.com/openaddresses/openaddresses/blob/master/sources/br/sc/statewide.json)) is not shown in green at http://results.openaddresses.io, and it is not accounted for in the coverage section, even though its coverage object seems to be filled in correctly.

**Comment by migurski** [comment]
Looks to me that the ISO code for Santa Catarina, BR-SC, is not present in Natural Earth’s ne_10m_admin_1_states_provinces dataset. I’ll fix our copy, and make a note upstream.
