### ISSUE TITLE
Add link to results page from Lost sources

### ISSUE THREAD

**Issue by trescube** [openaddresses/machine#597]
I've been going thru a lot of the lost sources recently and found myself having to copy/paste the source name from the dashboard to another tab open to https://results.openaddresses.io.  It would be really handy if the lost sources list source name was a link to that source's page on https://results.openaddresses.io.  For example, the first lost source is `sources/us/az/maricopa` and having that link to https://results.openaddresses.io/sources/us/az/maricopa would be really handy.  

In fact, having the `sources/` in `sources/us/az/maricopa` seems a little redundant since they're all sources.  Having links and source names similar to https://results.openaddresses.io/ would be more consistent.

**Comment by migurski** [comment]
I had a look at this, and I’m unsure how to change the D3 code to have this effect. Rather than changing the page to render based on data from the DB, I’ve reached to to @NelsonMinar for help understanding how D3 generates the table.
