### ISSUE TITLE
Add selected properties to dotmaps

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#618]
Add selected properties to dotmap Tippecanoe call. Omit hash!

Follow up to https://github.com/openaddresses/machine/pull/603. See also https://github.com/mapbox/tippecanoe/issues/403.

**Comment by ericfischer** [comment]
The Tippecanoe string pool performance should be much better after https://github.com/mapbox/tippecanoe/pull/463. Please let me know if you still see performance problems.

**Comment by migurski** [comment]
Thanks Eric! Sounds like we can upgrade to today’s version of Tippecanoe in our Dockerfile to take advantage of this? https://github.com/openaddresses/machine/blob/8e5331438/Dockerfile-prereqs#L19-L24
