### ISSUE TITLE
delete esri-outputs-csv branch?

### ISSUE THREAD

**Issue by NelsonMinar** [openaddresses/machine#62]
Nice job merging code to master @migurski! I think it's safe to delete our one remaining GitHub branch, esri-commits-csv, but am not doing it in case I'm confused. That contained 1-2 days work Ian and I did changing the ESRI parser from GeoJSON to CSV, it's done and merged now.

**Comment by migurski** [comment]
If @iandees says it’s okay I’ll go ahead.

**Comment by iandees** [comment]
Sure, looks good to delete. In fact I'll do it right now :).
