### ISSUE TITLE
Charts on dashboard are lacking time units

### ISSUE THREAD

**Issue by stefanb** [openaddresses/machine#634]
Charts on dashboard are lacking the time units.
Some (counts, dates) are intuitive, but cache or processing times are not.

Maybe the chart title should mention it at the end.

http://results.openaddresses.io/dashboard

**Comment by migurski** [comment]
Thanks for the suggestion! @NelsonMinar, would this be easy to add?

**Comment by NelsonMinar** [comment]
Yes but I can't get to it until this trip is over. The easiest thing would be to just add text to [the titles](https://github.com/openaddresses/machine/blob/master/openaddr/ci/templates/dashboard.html#L40). All time units are seconds.

When I get back I'll look into some nicer charting library; this thing I threw together is pretty limited.
