### ISSUE TITLE
Generate graphs of system resource usage over time

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#64]
`openaddr-process` should generate usage graphs of CPU, physical & swap memory, disk, and network over the course of its run, placing them in `/var/www/html` where `openaddr-ec2-run` can find them. I’ve messed around with _dstat_, _gnuplot_, and _munin_ enough to know it’s a rabbit hole for me. What tools exist for this and how can we get them added to the chef scripts?

**Comment by NelsonMinar** [comment]
The two ways I know to do this are Munin or custom code with D3. Munin requires a persistent monitoring node AFAIK. Custom D3 code would be easy enough with writing CSV files for resource usage. But what PITA. Maybe there's some off-the-shelf solution for EC2?

**Comment by NelsonMinar** [comment]
I'd also like some more basic longitudinal stats, like "rows in run" and "did this run complete successfully"? I think right now regressions like issue #74 are only visible to you.

**Comment by migurski** [comment]
Good point; the older versions have to be dug up.

**Comment by NelsonMinar** [comment]
I'm thinking I can cobble up a shot at part of this using the `state.txt` files we're writing. At least, a start on it; we're currently emitting the time it takes to cache and to process each output file and have a historical record.

**Comment by migurski** [comment]
Closing this issue, since we’ve changed our process enough to not require resource graphs.
