### ISSUE TITLE
`latest` image not tagged as such

### ISSUE THREAD

**Issue by trescube** [openaddresses/machine#641]
When I try running the [Running A Source Locally](https://github.com/openaddresses/machine/blob/master/docs/install.md#running-a-source-locally) instructions (on OSX), I get:

```
[stephenhess@slumlord tmp]$ docker run --volume `pwd`:/vol openaddr/machine openaddr-process-one -v vol/orange.json vol
Unable to find image 'openaddr/machine:latest' locally
docker: Error response from daemon: manifest for openaddr/machine:latest not found.
See 'docker run --help'.
```

If I specify `openaddr/machine:6.x`, it works.  It does respond with this, however:

```
[stephenhess@slumlord tmp]$ docker run --volume `pwd`:/vol openaddr/machine:6.x openaddr-process-one -v vol/orange.json vol
     1       278.2  DEBUG: Requesting https://github.com/datadesk/us-ca-orange_county-situs_parcels-shp/blob/master/situs_parcels.zip?raw=true with args None
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/util/__init__.py", line 306, in log_process_usage
    previous = log_current_usage(start_time, *previous)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/util/__init__.py", line 264, in log_current_usage
    pidlist = get_pidlist(getpid())
  File "/usr/local/lib/python3.4/dist-packages/openaddr/util/__init__.py", line 158, in get_pidlist
    children[int(ppid)].add(int(pid))
ValueError: invalid literal for int() with base 10: 'thread-self'
```

It runs to completion and the output looks good.

**Comment by trescube** [comment]
I'm on the latest Docker for OSX:  Version 17.03.1-ce-mac12 (17661)

**Comment by jalessio** [comment]
I don't see a `latest` tag for that repo on Docker hub:
https://hub.docker.com/r/openaddr/machine/tags/

AFAIK, the `latest` tag isn't special -- it's just an ordinary tag and you're responsible for tagging the images with `latest` yourself and pushing them to Docker Hub. I still haven't caught up with the project's migration to using Docker, but I would consider it a "best practice" to maintain a `latest` tag for users so they don't have to choose a version to pull an image from the Docker Hub.

**Comment by jalessio** [comment]
@trescube See PR #642 for a proposed solution.

**Comment by migurski** [comment]
`latest` tags are in: https://hub.docker.com/r/openaddr/machine/tags/
