### ISSUE TITLE
Add API retrieval for job information

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#666]
Get list of jobs for an existing region and data/status for an individual job.

- [ ] Wait for https://github.com/openaddresses/machine/issues/667
- [ ] https://github.com/mapzen/mobility-on-demand-sandbox-contributions/blob/master/docs/backend-requirements.md#retrieve-list-of-existing-sources-for-specified-region
- [ ] https://github.com/mapzen/mobility-on-demand-sandbox-contributions/blob/master/docs/backend-requirements.md#retrieve-all-job-information

**Comment by ingalls** [comment]
This is implemented in the Batch API which uses machine under the hood
Ref: https://batch.openaddresses.io/docs/
