### ISSUE TITLE
Add API for job updates

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#668]
Allow a user to update information about a job.

- [ ] Wait for https://github.com/openaddresses/machine/issues/667
- [ ] https://github.com/mapzen/mobility-on-demand-sandbox-contributions/blob/master/docs/backend-requirements.md#update-job

**Comment by ingalls** [comment]
This is implemented in the Batch API which uses machine under the hood
Ref: https://batch.openaddresses.io/docs/
