### ISSUE TITLE
Add API for job status updates

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#669]
Allow a user to get current preview status for a job and update it.

- [ ] Wait for https://github.com/openaddresses/machine/issues/668
- [ ] https://github.com/mapzen/mobility-on-demand-sandbox-contributions/blob/master/docs/backend-requirements.md#query-for-job-status
- [ ] Should a user be able to update job status manually? https://github.com/mapzen/mobility-on-demand-sandbox-contributions/blob/master/docs/backend-requirements.md#job-update-of-submission-status

**Comment by ingalls** [comment]
This is implemented in the Batch API which uses machine under the hood
Ref: https://batch.openaddresses.io/docs/
