### ISSUE TITLE
Source page has html title "Source whatever"

### ISSUE THREAD

**Issue by stefanb** [openaddresses/machine#674]
...instead of showing proper source country or other info.

https://github.com/openaddresses/machine/blob/2ff1770a2bf8b75c11d6338db202ac85253a43e9/openaddr/ci/templates/source.html#L2

Better just leave it at "Source" than have it "Source whatever" as it would look less buggy when sharing the links on social media

**Comment by migurski** [comment]
Good catch, thanks Stefan.

**Comment by stefanb** [comment]
Thank you!
