### ISSUE TITLE
Dotmaps not working due to missing mapzen resources

### ISSUE THREAD

**Issue by stefanb** [openaddresses/machine#697]
eg https://dotmaps.openaddresses.io/402659 (linked from http://results.openaddresses.io/jobs/f4fb6d56-328e-4fe0-b71b-822a9e22cf6f) gets 404 on essential 3rd party resources:
* https://mapzen.com/js/mapzen.css and
* https://mapzen.com/js/mapzen.min.js

resulting in javascript error in console:
```
(index):92 Uncaught ReferenceError: L is not defined
    at (index):92
```
...and page remaining blank instead of showing the map.

**Comment by andrewharvey** [comment]
There are two different fixes proposed for this:

https://github.com/openaddresses/dotmaps/pull/1
https://github.com/openaddresses/dotmaps/pull/2

**Comment by stefanb** [comment]
Okay, thanks for the pointer. I guess then there's no need to keep tracking it here as well.

**Comment by nvkelso** [comment]
I think those are both hosted at nextzen.org now...
