### ISSUE TITLE
Kosovo is not coloured green on the map, missing from coverage

### ISSUE THREAD

**Issue by stefanb** [openaddresses/machine#700]
After https://github.com/openaddresses/openaddresses/pull/3866
was merged imports seem to be running fine:
http://results.openaddresses.io/sources/xk/countrywide
but
* the map stays blank for Kosovo (see eg http://results.openaddresses.io/sets/402797/ )
![image](https://user-images.githubusercontent.com/319826/38876568-fe9e7316-425c-11e8-8710-61816348ab67.png)
* there is no mention of Kosovo in coverage report: http://results.openaddresses.io/coverage/world/

Perhaps there is some misalignment in the ISO country code `XK` vs `KV` ?

The map on the main page https://openaddresses.io/ is showing the addresses nicely.

Is machine respecting strictly just [ISO-assigned 2-letter country codes](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) and is not knowing either of those?

**Comment by migurski** [comment]
I think I see the problem: our Natural Earth countries dataset does not include an ISO 2-letter code for Kosovo. I’ll fix it in our copy. /cc @nvkelso

**Comment by stefanb** [comment]
It would be nice to either:
* check for valid country code during source json validation or
* generate a warning during batch run

**Comment by stefanb** [comment]
In the coverage table on http://results.openaddresses.io/coverage/world/ there is still no sign of Kosovo.

Validating the code would make sense only if there is no geometry defined in the source json, so that machine make sure that it understands the coverage.
