### ISSUE TITLE
Toronto data missing city name

### ISSUE THREAD

**Issue by Valachio** [openaddresses/machine#709]
First of all.  This project is a godsend.  Thank you for your great work.

I'm referring to this dataset - http://results.openaddresses.io/sources/ca/on/city_of_toronto

The dataset is missing the district names (Scarborough, Etobicoke, North York, York, and East York)

Toronto is technically one large municipality after an amalgamation in 1998, but people still refer to the former districts by their names.  Partly because the amalgamation created duplicate addresses.

E.g. There is a 6 Church Street, North York _and_ 6 Church Street, Toronto

The address data provided by Open Data Toronto has the district name of each address.  I believe it should be available through the source you guys download the data through as well.

**Comment by Valachio** [comment]
@iandees My fault.  Thank you for responding quickly

We will try to help with Canadian addresses wherever we can (we are building real estate app for Canada).  Keep this project alive and strong!  It's one of its kind and incredibly valuable to people.

**Comment by migurski** [comment]
Thanks for saying so, @Valachio!

I looked at the city name in the data, and the most common value is “former Toronto”. Does that sound right to you?

```
	Most common values:    former Toronto (157401x)
	                       Scarborough (123906x)
	                       North York (114222x)
	                       Etobicoke (73521x)
	                       York (32476x)
```

**Comment by Valachio** [comment]
@migurski You can safely change "_former Toronto_" to just "_Toronto_".

Former Toronto in this case refers to the original part of Toronto before amalgamation.

**Comment by migurski** [comment]
Thanks for the explanation. I think we should leave this alone so we’re not special-casing places, but I appreciate the local history check.
