### ISSUE TITLE
Add Esri source conversion convenience script

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#71]
`EsriRestDownloadTask` looks to be one of the few things that can read data from an ESRI feature service like http://maps.indy.gov/ArcGIS10a/rest/services/MyNeighborhoodSelection/MapServer/2. @daguar suggests wrapping it with a script that can pull out GeoJSON.

**Comment by iandees** [comment]
It might make more sense to extract the ESRI stuff into a library (replacing the stuff in https://github.com/iandees/esri-dump) and give it a command line client.

**Comment by migurski** [comment]
That makes sense. Why don’t I start it here, and then we can move it there?

**Comment by iandees** [comment]
Yep, definitely. Whatever's easiest and makes it happen.

**Comment by migurski** [comment]
Made some progress this morning in [esri2geojson.py](https://github.com/openaddresses/machine/blob/e8855ad5f85e3b0df0e0704f7769a02d1520ef67/openaddr/util/esri2geojson.py#L92).
