### ISSUE TITLE
Requesting an email list for batch completion notifications

### ISSUE THREAD

**Issue by colin-umn** [openaddresses/machine#720]
Hi - I am submitting this to request that an email list be set up to notify subscribers that a new batch is complete.  The use case is that, after making a change, I repeatedly check the site for the batch status.  If I could subscribe to an email, that would make my web site checks unnecessary.

Thanks.
Colin

**Comment by migurski** [comment]
Hi Colin, thanks for getting in touch. This might be something we can accommodate, but maybe there’s a non-email way to do it. For example, do you use RSS?

**Comment by colin-umn** [comment]
Hi Michal,

Background: I initiated this request after sending an email to
hello@openaddresses.io asking if such an email list exists.  Ian Dees
replied and said that none exists but suggested that I create an issue
since it might be a good idea.

I am actually not in the habit of using RSS.  I am guessing not a high
percentage of others use it much anymore either.

If I am the only one who would be interested in such an email list, I would
not be offended at your closing this issue.  I just wanted to make use of
such an email list if it did exist.

Thanks.
Colin

**Comment by migurski** [comment]
We do currently send notification emails when various events occur in OpenAddresses: aside from batch completion, there are also notifications about new zip files and servers going up and down. These are intended for internal use but I’d be happy to add you to the list if you’re willing to filter it down to just the things you need. It’s on the order of 5-10 messages per day.

**Comment by colin-umn** [comment]
Thanks Michal, but I think I'll pass on the higher volume list.  I'll just
keep checking the site periodically when waiting for a new batch.

Colin

**Comment by migurski** [comment]
Sounds good! I’ll keep an eye on other uses cases for determining batch completion.
