### ISSUE TITLE
Rename X/Y columns in extracted CSV

### ISSUE THREAD

**Issue by NelsonMinar** [openaddresses/machine#73]
The intermediate CSV we generate with latitude and longitude added has the lat/lon columns hardcoded to "X" and "Y". Let's rename those to something that won't collide. @migurski got most of this done but ran into some weirdness in the tests, see https://github.com/openaddresses/machine/commit/6137020daf2f264d54742b655192c16ad4d33e14#commitcomment-9862218

**Comment by NelsonMinar** [comment]
I found the source of the [problem](https://github.com/openaddresses/machine/commit/6137020daf2f264d54742b655192c16ad4d33e14#commitcomment-9862218) with renaming the CSV fields for X/Y in cached output. The tests don't catch it; it's reproducible by changing `X_FIELDNAME` to something else in the code and running `openaddr-process-one` on any live ESRI source. `us-mn-wilkin.json` is a good short and fast one.

The issue is that the source conform specification includes names for columns for lat/lon. But unless the original source is CSV there's no need for the user to name those columns. The geometry object is implicitly findable in other types like Shapefiles and we make up our own column names `X_FIELDNAME`, etc. In other words the ESRI downloader code is correctly naming the column `X_FIELDNAME`, but `us-mn-wilkin.json` is still saying it's named `X`.

My proposed solution is to change the spec for conform JSON in the product. Any thoughts?

1. Modify the Python conform code to ignore the lat/lon tags in source conform specs unless the source type is CSV.
2. Change [the docs](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#attribute-tags) to indicate lat/lon tags are only for CSV sources.
3. For CSV types check that the "extracted" CSV file rewrites whatever column name was in the original source to the new `X_FIELDNAME` column.

(I don't know what the Node code will do if it encounters a source file without the lat/lon columns. If it doesn't work, it'd be as simple as assuming they're named `X` and `Y` if not specified.)

**Comment by migurski** [comment]
I like this approach. How does it interact with the CSV’s that come from cached Esri sources?

**Comment by NelsonMinar** [comment]
OK I'll implement it tomorrow. No idea about "cached" (we don't read from cache, do we?) but for the ESRI sources we download the downloader will write the X_FIELDNAME columns which we then read.

**Comment by migurski** [comment]
Great that makes sense. I can supply whatever test files you might need, if that’d be useful?

**Comment by NelsonMinar** [comment]
There's a related problem in the way the conform spec works. ESRI sources are identified with `type: ESRI` and `conform/type: geojson`. But the `conform/type` tag is completely superfluous (and we ignore it).

**Comment by NelsonMinar** [comment]
I've committed [a branch](https://github.com/openaddresses/machine/tree/rename-x-y) to use `OA:x` and `OA:y` as column names. @migurski could you please review it? The Carson tests in `TestOA` need updating. I think it's simple but I'm a bit afraid to do that myself.

This change got complicated. The problem here is a lot of tests and test data assumed CSV files with `X`, not `OA:x`. I think I got them all except the Carson tests.

 (Ignore 90c7f42; was a mistake, removed from the repo.)

**Comment by migurski** [comment]
Great—I’ll be able to give it a detailed look likely tomorrow.

**Comment by NelsonMinar** [comment]
gentle reminder @migurski to look at this. if you just read through the code quick I can fix the tests.

**Comment by NelsonMinar** [comment]
Ping @migurski? I may just finish this on my own and commit it in a few days if you don't have time to look at it.

**Comment by migurski** [comment]
Oops, sorry. I’m thinking to look at a few changes this weekend.

**Comment by migurski** [comment]
See PR #86. @NelsonMinar, I found it necessary to explicitly look for ESRI-sourced CSV in the conform function. The conform objects that come with ESRI and other non-CSV sources are full of lies, and it might be wise in the long term to remove `lat` and `lon` from the [list of required attribute tags](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#attribute-tags) since they’re ignored in all non-CSV cases.

**Comment by NelsonMinar** [comment]
I've made a pull request to update the documentation of the conform spec; this was [step 2 in the plan](https://github.com/openaddresses/machine/issues/73#issuecomment-75820836).

**Comment by migurski** [comment]
For sure—I missed that the plan was right here when I scrolled through this issue. Sorry about that, we're in agreement that natively-geographic sources like ESRI or shapefile should not have lat/lon specified.
