### ISSUE TITLE
Investigate new failures in AU, NL, and DK

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#74]
Between [Feb 16](http://data.openaddresses.io/runs/1424070358.882/index.html) and [Feb 18](http://data.openaddresses.io/runs/1424243321.101/index.html), many sources started to fail. Seemingly this corresponds to [release 1.4.1](https://github.com/openaddresses/machine/blob/master/CHANGELOG), “detection of geometry type in ESRI sources.” We’re seeing success rates of ~495 sources instead of previous ~510.

We are also seeing intermittent failures in Denmark and Netherlands.

**Comment by NelsonMinar** [comment]
I think 3 of these 4 are timeouts from slow runs, maybe optimizations from issue #65 will help? `nl.json` and `au-victoria.json` timed out after nearly 2 hours of CPU processing. That doesn't surprise me, they've always been big/slow jobs. `nl.json` at least is CPU bound, just a lot of data. `dk.json` ran successfully last time, so I can't check for errors. IIRC it's like `nl.json` in being CPU bound though, were previous failures timeouts?

au-queensland failed on a [real error](http://data.openaddresses.io/runs/1424675318.029/au-queensland.txt). It's still failing on my machine, didn't look into exactly why.

**Comment by migurski** [comment]
Sounds like I should bring the timeout to 3 hours before tonight's Wednesday run.

**Comment by NelsonMinar** [comment]
Worth a try. FWIW all three take 30–45 minutes on my unloaded home machine. It's almost all CPU time.

**Comment by migurski** [comment]
Back to [111m addresses](http://data.openaddresses.io/runs/1424849197.715/index.html).

**Comment by migurski** [comment]
Closing this; opened a new issue #95 for Queensland, Australia.
