### ISSUE TITLE
Add US render back to output

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#77]
…to facilitate US debugging.

**Comment by iandees** [comment]
:us: :us:

**Comment by NelsonMinar** [comment]
Would it be useful to have a zoomable map view? If you can emit some sort of shapes for the colored regions I'll cobble up a Leaflet map. Or maybe a GeoJSON already exists?

**Comment by migurski** [comment]
Might be—there are already shapefiles in the repository, if you want to start with those. I’ve typically found the zoomable versions a bit less informative than the static ones here, but I think it’d be possible to crank out both.

**Comment by migurski** [comment]
Where we’re at currently:

![out](https://cloud.githubusercontent.com/assets/58730/6559711/0005474c-c642-11e4-93d5-2bf28b20037a.png)

**Comment by NelsonMinar** [comment]
Just for comparison, here's what the [Fairview data layer](http://fairview-industries.com/page7/page7.html) says is available for county data (from Mike's image).

![screen shot 2015-03-09 at 10 10 09 am](https://cloud.githubusercontent.com/assets/382136/6560073/90d38b9c-c644-11e4-9175-458a81bd5be8.png)

**Comment by iandees** [comment]
FWIW, I spent a good part of the weekend looking through the Fairview data and a large majority of the URLs they have listed are either 404s or don't contain address data.

**Comment by migurski** [comment]
Should we therefore stub out files for those counties, with `skip=true` and a note?

**Comment by iandees** [comment]
Yea, it might make sense to auto-generate all the county-level sources.

If we do that, we probably should break up the `sources/` dir into separate dirs for region/states if it would be feasible for machine to support it.

**Comment by migurski** [comment]
I don’t think I’ve ever tried to run it with subdirectories, but it should be relatively easy to make that work.

**Comment by NelsonMinar** [comment]
I really don't like the idea of mixing auto-generated source files that don't work with hand-edited personally contributed files that do work, or have some reason to think could work. If we go this route there should be some way to communicate the provenance of the file, either a separate directory or else a comment in the JSON. (We're way off topic for this issue, sorry I started a de-rail.)
