### ISSUE TITLE
Add city and region to output CSV

### ISSUE THREAD

**Issue by NelsonMinar** [openaddresses/machine#82]
We just added `postcode` to the final CSV output (#79). Discussion in Slack was a rough consensus to adding `city` and `region` to the CSV output as well. This will help a lot for the whole-state files like `us-ny` and whole-country files like `nl`

Those columns should be empty unless the conform object names a property that has them.

Adding this data is going to greatly increase the output file size. I think we should do compression (issue #56) first.

**Comment by iandees** [comment]
Check out the [CONTRIBUTING.md](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#attribute-tags) doc on the openaddresses repo. We might want to include `district` as well.

**Comment by migurski** [comment]
Done in #106.
