### ISSUE TITLE
Unzip only the files that are needed

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#87]
We are seeing new job timeouts in Poland because machine is pulling all GML files out of a zip archive, even though only one is needed. See http://data.openaddresses.io/runs/1426486295.818/pl-lodzkie.txt.

**Comment by NelsonMinar** [comment]
See also https://github.com/openaddresses/openaddresses/pull/872 where we tried to split the Poland sources up.  Not sure if it's complete.

**Comment by migurski** [comment]
Merged @kelvinabrokwa’s PR.
