### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by astoff** [openaddresses/machine#89]
Some words follow special capitalization rules.  For instance, prepositions should be lowercase, and roman numeral all caps ("Rua do Arvoredo", "Rua João XXIII").

The abbreviation expansion algorithm should operate in a way that it can also be used to fine tune capitalization when needed.

**Comment by migurski** [comment]
Thank you @astoff. I’m unsure how to best approach this, because there are many such cultural and linguistic cases around the world. I’m going to flag this as _help wanted_, because we really might need experts in various areas correcting the conform rules.

**Comment by NelsonMinar** [comment]
See also Consider not rewriting street names #32. Totally agree if we rewrite names, we need to do so much more intelligently. And it has to be locale-aware.

**Comment by astoff** [comment]
These questions are tracked elsewhere now, so closing this issue.
