### ISSUE TITLE
Use older cached data

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#9]
From [11/22](http://data.openaddresses.io/runs/1416691007.107/index.html) to [11/27](http://data.openaddresses.io/runs/1417104661.353/index.html), some number of previously-cached data files disappeared. Older data should be used if newer data is not available.

**Comment by migurski** [comment]
Followup example:

* http://data.openaddresses.io/runs/1429078303.772/us-ut.txt
* http://data.openaddresses.io.s3.amazonaws.com/us-ut.zip

**Comment by ingalls** [comment]
Done!
