### ISSUE TITLE
Sources incorrectly marked as "missing conform" on data.openaddresses.io

### ISSUE THREAD

**Issue by kelvinabrokwa** [openaddresses/machine#90]
There are a number of sources with a `conform` object that come up as "missing conform" on [data.openaddresses.io](http://data.openaddresses.io). Here are some that I've noticed:

- [us-ca-madera-county.json](https://github.com/openaddresses/openaddresses/blob/master/sources/us-ca-madera_county.json)
- [us-ca-orange_county.json](https://github.com/openaddresses/openaddresses/blob/master/sources/us-ca-orange_county.json)
- [us-ca-san_joaquin_county.json](https://github.com/openaddresses/openaddresses/blob/master/sources/us-ca-san_joaquin_county.json)
- [us-ct-city_of_manchester.json](https://github.com/openaddresses/openaddresses/blob/master/sources/us-ct-city_of_manchester.json)
- [us-ct-town_of_groton.json](https://github.com/openaddresses/openaddresses/blob/master/sources/us-ct-town_of_groton.json)

I'm not quite sure what is causing this (or if it even originates in machine) but I thought I should bring it up. If this is a result of invalid conform objects then it would show up in the log, no?

**Comment by migurski** [comment]
I was puzzled by this as well, then noticed that data.openaddresses.io is one week old. I’m unsure why that is, so I’m running one to figure out why it might be stopping early. I suspect there’s some bug that’s causing it to exit early.

**Comment by migurski** [comment]
I dug into this a little more deeply, and I believe what’s happening is that the current EC2 spot price is fluctuating and our instance is getting kneecapped. I don’t believe we can do much about this aside from simply bidding more, so I’m going to do a run at a very high bid price just so we can have something up for this week.

![spot-pricing](https://cloud.githubusercontent.com/assets/58730/6908689/dc1f6b06-d6f3-11e4-9b9f-6d291a106ca2.png)

**Comment by kelvinabrokwa** [comment]
Cool, thanks for looking into it.
